const data = [
  {
    "OBJECTID": 1,
    "NAME": "SOMERSET",
    "ADDRESS": "300 REFINERY ROAD",
    "CITY": "SOMERSET",
    "STATE": "KY",
    "TYPE": "VERY SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 34,
    "COUNTY": "PULASKI",
    "LATITUDE": 37.07113,
    "LONGITUDE": -84.60951,
    "WEBSITE": "http://www.continentalrefiningco.com",
    "OWNER": "CONTINENTAL REFINING CO LLC",
    "OPERNAME": "CONTINENTAL REFINING COMPANY LLC",
    "CAPACITY": 5500,
    "US_RANK": 134,
    "CRUDE": 5500,
    "IMAGE": "https://drive.google.com/uc?id=1ry_aDJNOTRsWp0aYv4q7Aq8UcYON2iFm"
  },
  {
    "OBJECTID": 2,
    "NAME": "WOODS CROSS",
    "ADDRESS": "2355 SOUTH 1100 WEST",
    "CITY": "WOODS CROSS",
    "STATE": "UT",
    "TYPE": "VERY SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 45,
    "COUNTY": "DAVIS",
    "LATITUDE": 40.86776,
    "LONGITUDE": -111.91,
    "WEBSITE": "http://silvereagleenergy.com",
    "OWNER": "SILVER EAGLE REFINING INC",
    "OPERNAME": "SILVER EAGLE REFINING",
    "CAPACITY": 15000,
    "US_RANK": 122,
    "CRUDE": 15000,
    "IMAGE": "https://drive.google.com/uc?id=1r6yLIb9_pLLFhtV1_Z3d4BHaN8YqTmSD"
  },
  {
    "OBJECTID": 3,
    "NAME": "COMMERCE CITY EAST",
    "ADDRESS": "5801 BRIGHTON BLVD",
    "CITY": "COMMERCE CITY",
    "STATE": "CO",
    "TYPE": "SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 420,
    "COUNTY": "ADAMS",
    "LATITUDE": 39.80175,
    "LONGITUDE": -104.94518,
    "WEBSITE": "http://www.suncor.com",
    "OWNER": "SUNCOR ENERGY INC",
    "OPERNAME": "SUNCOR ENERGY (USA) INC",
    "CAPACITY": 36000,
    "US_RANK": 107,
    "CRUDE": 36000,
    "IMAGE": "https://drive.google.com/uc?id=1WytDZWQOPkbOXcbM0CQvnfmLs8Ul15fR"
  },
  {
    "OBJECTID": 4,
    "NAME": "SAN ANTONIO",
    "ADDRESS": "7811 S PRESA STREET",
    "CITY": "SAN ANTONIO",
    "STATE": "TX",
    "TYPE": "SMALL LUBRICANTS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 50,
    "COUNTY": "BEXAR",
    "LATITUDE": 29.34757,
    "LONGITUDE": -98.46019,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET LUBRICANTS CO",
    "CAPACITY": 20000,
    "US_RANK": 117,
    "CRUDE": 20000,
    "IMAGE": "https://drive.google.com/uc?id=1CjOUqZR2XolRmj6Z4X4W26jjwKll6pBW"
  },
  {
    "OBJECTID": 5,
    "NAME": "PAULSBORO",
    "ADDRESS": "800 BILLINGSPORT ROAD",
    "CITY": "PAULSBORO",
    "STATE": "NJ",
    "TYPE": "LARGE HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 427,
    "COUNTY": "GLOUCESTER",
    "LATITUDE": 39.84038,
    "LONGITUDE": -75.25681,
    "WEBSITE": "http://www.pbfenergy.com",
    "OWNER": "PBF ENERGY CO LLC",
    "OPERNAME": "PAULSBORO REFINING CO LLC",
    "CAPACITY": 160000,
    "US_RANK": 44,
    "CRUDE": 160000,
    "IMAGE": "https://drive.google.com/uc?id=18to-xjaj-Vp3NMEZYfxRYQKd_9tgnDfz"
  },
  {
    "OBJECTID": 6,
    "NAME": "TEXAS CITY",
    "ADDRESS": "1301 LOOP 197 SOUTH",
    "CITY": "TEXAS CITY",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 509,
    "COUNTY": "GALVESTON",
    "LATITUDE": 29.36763,
    "LONGITUDE": -94.90828,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO TEXAS LP",
    "CAPACITY": 225000,
    "US_RANK": 32,
    "CRUDE": 225000,
    "IMAGE": "https://drive.google.com/uc?id=1xA6wCQjpRpZ0FRWB7eo6Jpw-Mnoa04sv"
  },
  {
    "OBJECTID": 7,
    "NAME": "TEXAS CITY",
    "ADDRESS": "502 10TH STREET SOUTH",
    "CITY": "TEXAS CITY",
    "STATE": "TX",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY THAT PROCESSES SWEET CRUDE",
    "STATUS": "IN SERVICE",
    "POPULATION": 276,
    "COUNTY": "GALVESTON",
    "LATITUDE": 29.37542,
    "LONGITUDE": -94.90798,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 86000,
    "US_RANK": 73,
    "CRUDE": 86000,
    "IMAGE": "https://drive.google.com/uc?id=1jSD9cUZb7laGJGzKO_mINdR28FBy8kIG"
  },
  {
    "OBJECTID": 8,
    "NAME": "BAYTOWN",
    "ADDRESS": "2800 DECKER DR/4500 BAYWAY DRIVE",
    "CITY": "BAYTOWN",
    "STATE": "TX",
    "TYPE": "VERY LARGE AND HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1307,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.74285,
    "LONGITUDE": -95.01026,
    "WEBSITE": "http://www.exxonmobilchemical.com",
    "OWNER": "EXXON MOBIL CORP",
    "OPERNAME": "EXXONMOBIL REFINING & SUPPLY CO",
    "CAPACITY": 560500,
    "US_RANK": 2,
    "CRUDE": 560500,
    "IMAGE": "https://drive.google.com/uc?id=14QB6hIKqkCMwp497fr3g3mqSvGaDWnU5"
  },
  {
    "OBJECTID": 9,
    "NAME": "CHALMETTE",
    "ADDRESS": "500 WEST ST. BERNARD HWY",
    "CITY": "CHALMETTE",
    "STATE": "LA",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 625,
    "COUNTY": "ST. BERNARD",
    "LATITUDE": 29.93358,
    "LONGITUDE": -89.96916,
    "WEBSITE": "http://corporate.exxonmobil.com",
    "OWNER": "PBF ENERGY CO LLC",
    "OPERNAME": "CHALMETTE REFINING LLC",
    "CAPACITY": 190000,
    "US_RANK": 37,
    "CRUDE": 190000,
    "IMAGE": "https://drive.google.com/uc?id=1Wadf3nQyhN4InZcG3CFWG2unTysYoyxM"
  },
  {
    "OBJECTID": 10,
    "NAME": "TOLEDO",
    "ADDRESS": "4001 CEDAR POINT ROAD",
    "CITY": "OREGON",
    "STATE": "OH",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 465,
    "COUNTY": "LUCAS",
    "LATITUDE": 41.67947,
    "LONGITUDE": -83.45156,
    "WEBSITE": "http://www.huskyenergy.com",
    "OWNER": "BP HUSKY REFINING LLC",
    "OPERNAME": "BP-HUSKY REFINING LLC",
    "CAPACITY": 153000,
    "US_RANK": 48,
    "CRUDE": 153000,
    "IMAGE": "https://drive.google.com/uc?id=1BJ_RRlvX0pQKQy8TyDoywLnO1nM8pvKZ"
  },
  {
    "OBJECTID": 11,
    "NAME": "THREE RIVERS",
    "ADDRESS": "301 LEROY STREET",
    "CITY": "THREE RIVERS",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 302,
    "COUNTY": "LIVE OAK",
    "LATITUDE": 28.45728,
    "LONGITUDE": -98.18771,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO ENERGY CORPORATION",
    "CAPACITY": 89000,
    "US_RANK": 71,
    "CRUDE": 89000,
    "IMAGE": "https://drive.google.com/uc?id=18NM1-XN2oCN0i6zmLKAcY1nsxT6fG_2J"
  },
  {
    "OBJECTID": 12,
    "NAME": "HOUSTON",
    "ADDRESS": "9701 MANCHESTER",
    "CITY": "HOUSTON",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 340,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.72181,
    "LONGITUDE": -95.2536,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO TEXAS LP",
    "CAPACITY": 191000,
    "US_RANK": 36,
    "CRUDE": 191000,
    "IMAGE": "https://drive.google.com/uc?id=1IZa-Uno28T_YgNIIwqH5jPUh_wqR4Dss"
  },
  {
    "OBJECTID": 13,
    "NAME": "SINCLAIR",
    "ADDRESS": "100 E LINCOLN AVENUE (EAST LINCOLN HIGHWAY)",
    "CITY": "SINCLAIR",
    "STATE": "WY",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 332,
    "COUNTY": "CARBON",
    "LATITUDE": 41.78212,
    "LONGITUDE": -107.10722,
    "WEBSITE": "http://www.sinclairoil.com",
    "OWNER": "SINCLAIR OIL CORP",
    "OPERNAME": "SINCLAIR WYOMING REFINING CO",
    "CAPACITY": 85000,
    "US_RANK": 76,
    "CRUDE": 85000,
    "IMAGE": "https://drive.google.com/uc?id=1Y5Ix-v9nt9zcN8bV4bMLZNt9V7KACxlF"
  },
  {
    "OBJECTID": 14,
    "NAME": "TYLER",
    "ADDRESS": "1702 E COMMERCE STREET",
    "CITY": "TYLER",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 254,
    "COUNTY": "SMITH",
    "LATITUDE": 32.36172,
    "LONGITUDE": -95.2797,
    "WEBSITE": "http://www.delekus.com",
    "OWNER": "DELEK GROUP LTD",
    "OPERNAME": "DELEK REFINING LTD",
    "CAPACITY": 72000,
    "US_RANK": 86,
    "CRUDE": 72000,
    "IMAGE": "https://drive.google.com/uc?id=1XSGIoHnmm1q18Kh-fIA-QPn48SJr6_yb"
  },
  {
    "OBJECTID": 15,
    "NAME": "MARTINEZ",
    "ADDRESS": "3485 PACHECO BLVD",
    "CITY": "MARTINEZ",
    "STATE": "CA",
    "TYPE": "LARGE HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 774,
    "COUNTY": "CONTRA COSTA",
    "LATITUDE": 38.01844,
    "LONGITUDE": -122.11327,
    "WEBSITE": "http://www.shell.us",
    "OWNER": "ROYAL DUTCH/SHELL GROUP",
    "OPERNAME": "SHELL OIL PRODUCTS US",
    "CAPACITY": 156400,
    "US_RANK": 47,
    "CRUDE": 156400,
    "IMAGE": "https://drive.google.com/uc?id=1Sn3HlimgjXqeQC2dfUngSzhRBvZNfKh4"
  },
  {
    "OBJECTID": 16,
    "NAME": "SUNRAY",
    "ADDRESS": "6701 FM 119",
    "CITY": "SUNRAY",
    "STATE": "TX",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 435,
    "COUNTY": "MOORE",
    "LATITUDE": 35.95528,
    "LONGITUDE": -101.88038,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO ENERGY CORPORATION",
    "CAPACITY": 195000,
    "US_RANK": 35,
    "CRUDE": 195000,
    "IMAGE": "https://drive.google.com/uc?id=10EInuOepaeGGvxMpsGOi4ADEojGWlRxS"
  },
  {
    "OBJECTID": 17,
    "NAME": "PASADENA",
    "ADDRESS": "111 RED BLUFF ROAD",
    "CITY": "PASADENA",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY WITH A HIGH GASOLINE YIELD",
    "STATUS": "IN SERVICE",
    "POPULATION": 345,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.7231,
    "LONGITUDE": -95.20804,
    "WEBSITE": "http://www.petrobras.com",
    "OWNER": "PETROBRAS AMERICA INC",
    "OPERNAME": "PASADENA REFINING SYSTEMS INC",
    "CAPACITY": 112229,
    "US_RANK": 61,
    "CRUDE": 112229,
    "IMAGE": "https://drive.google.com/uc?id=1FwVJm8S0BY_vZfcSvwGr4C3i7voWeJGm"
  },
  {
    "OBJECTID": 18,
    "NAME": "LAKE CHARLES",
    "ADDRESS": "1601 HWY 108 E",
    "CITY": "SULPHUR",
    "STATE": "LA",
    "TYPE": "MODERN DEEP-CONVERSION FACILITY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1183,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.17866697,
    "LONGITUDE": -93.33023518,
    "WEBSITE": "http://citgorefining.com",
    "OWNER": "PDV AMERICA INC",
    "OPERNAME": "CITGO PETROLEUM CORP",
    "CAPACITY": 425000,
    "US_RANK": 6,
    "CRUDE": 425000,
    "IMAGE": "https://drive.google.com/uc?id=1QixJBHR9UiyQEZfUVhCh7hFGhkxt49Bd"
  },
  {
    "OBJECTID": 19,
    "NAME": "RODEO (SAN FRANCISCO)",
    "ADDRESS": "1380 SAN PABLO AVENUE",
    "CITY": "RODEO",
    "STATE": "CA",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 445,
    "COUNTY": "CONTRA COSTA",
    "LATITUDE": 38.04457,
    "LONGITUDE": -122.25522,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 120200,
    "US_RANK": 58,
    "CRUDE": 120200,
    "IMAGE": "https://drive.google.com/uc?id=1AdUV-_F-RywbRPkCckJ0fLxIqUGA86Js"
  },
  {
    "OBJECTID": 20,
    "NAME": "TULSA WEST",
    "ADDRESS": "1700 S UNION AVE",
    "CITY": "TULSA",
    "STATE": "OK",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 285,
    "COUNTY": "TULSA",
    "LATITUDE": 36.1389,
    "LONGITUDE": -96.02106,
    "WEBSITE": "http://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER TULSA REFINING LLC",
    "CAPACITY": 85000,
    "US_RANK": 75,
    "CRUDE": 85000,
    "IMAGE": "https://drive.google.com/uc?id=1kYAyn7jskWjFYrBgkcyJfbosFAPi8yMN"
  },
  {
    "OBJECTID": 21,
    "NAME": "PARAMOUNT",
    "ADDRESS": "14700 DOWNEY AVENUE",
    "CITY": "PARAMOUNT",
    "STATE": "CA",
    "TYPE": "SMALL LOW COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 155,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.89872,
    "LONGITUDE": -118.14659,
    "WEBSITE": "http://www.ppcla.com",
    "OWNER": "ALON ISRAEL OIL COMPANY LTD",
    "OPERNAME": "PARAMOUNT PETROLEUM CORPORATION",
    "CAPACITY": 84500,
    "US_RANK": 77,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1u6PnW9BK1_Nddld4-db_BAHd-Gujo1T8"
  },
  {
    "OBJECTID": 22,
    "NAME": "TULSA EAST",
    "ADDRESS": "902 W 25TH STREET",
    "CITY": "TULSA",
    "STATE": "OK",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 409,
    "COUNTY": "TULSA",
    "LATITUDE": 36.11992,
    "LONGITUDE": -96.00072,
    "WEBSITE": "https://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER TULSA REFINING LLC",
    "CAPACITY": 70300,
    "US_RANK": 87,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=14exyojSyo0WDVDzHz44aKjSEMySURH6d"
  },
  {
    "OBJECTID": 23,
    "NAME": "MOUNT VERNON",
    "ADDRESS": "1200 REFINERY ROAD",
    "CITY": "MOUNT VERNON",
    "STATE": "IN",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 190,
    "COUNTY": "POSEY",
    "LATITUDE": 37.94216,
    "LONGITUDE": -87.91082,
    "WEBSITE": "http://www.countrymark.com",
    "OWNER": "COUNTRYMARK COOP INC",
    "OPERNAME": "COUNTRYMARK COOPERATIVE INC",
    "CAPACITY": 28200,
    "US_RANK": 110,
    "CRUDE": 28200,
    "IMAGE": "https://drive.google.com/uc?id=1lnJBsu6kj0WVO3xePClQ_itiHPR4KB7K"
  },
  {
    "OBJECTID": 24,
    "NAME": "NEWELL",
    "ADDRESS": "9995 OHIO RIVER BOULEVARD",
    "CITY": "NEWELL",
    "STATE": "WV",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 180,
    "COUNTY": "HANCOCK",
    "LATITUDE": 40.61127,
    "LONGITUDE": -80.62966,
    "WEBSITE": "http://www.ergon.com/",
    "OWNER": "ERGON INC",
    "OPERNAME": "ERGON WEST VIRGINIA INC",
    "CAPACITY": 22300,
    "US_RANK": 116,
    "CRUDE": 22300,
    "IMAGE": "https://drive.google.com/uc?id=1_hhUEK-lcUaC7b8Ufi7bjOnNTheMpAS_"
  },
  {
    "OBJECTID": 25,
    "NAME": "WESTLAKE",
    "ADDRESS": "2800 OLD SPANISH TRAIL",
    "CITY": "WESTLAKE",
    "STATE": "LA",
    "TYPE": "MEDIUM LUBRICANTS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 98,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.24224,
    "LONGITUDE": -93.28476,
    "WEBSITE": "http://www.fhr.com",
    "OWNER": "EXCEL PARALUBES",
    "OPERNAME": "EXCEL PARALUBES",
    "CAPACITY": 0,
    "US_RANK": 139,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=15pw7OoQVRQeCv3rYqBa_nXghNC3iFhj2"
  },
  {
    "OBJECTID": 26,
    "NAME": "WESTLAKE",
    "ADDRESS": "2200 OLD SPANISH TRAIL",
    "CITY": "WESTLAKE",
    "STATE": "LA",
    "TYPE": "LARGE MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 705,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.24116,
    "LONGITUDE": -93.27022,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 260000,
    "US_RANK": 21,
    "CRUDE": 260000,
    "IMAGE": "https://drive.google.com/uc?id=1_PQkZuMPKO0l4Q_tAB4mC5aReGAtAHmw"
  },
  {
    "OBJECTID": 27,
    "NAME": "SAINT PAUL PARK",
    "ADDRESS": "301 ST PAUL PARK RD",
    "CITY": "SAINT PAUL PARK",
    "STATE": "MN",
    "TYPE": "MEDIUM REFINERY WITH HIGH COMPLEXITY",
    "STATUS": "IN SERVICE",
    "POPULATION": 370,
    "COUNTY": "WASHINGTON",
    "LATITUDE": 44.85156,
    "LONGITUDE": -93.00051,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 102000,
    "US_RANK": 63,
    "CRUDE": 98515,
    "IMAGE": "https://drive.google.com/uc?id=1nd86st-whT6hzugm5sMGFHq1Nq-qZUk5"
  },
  {
    "OBJECTID": 28,
    "NAME": "BRADFORD",
    "ADDRESS": "77 N KENDALL AVE",
    "CITY": "BRADFORD",
    "STATE": "PA",
    "TYPE": "VERY SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 250,
    "COUNTY": "MCKEAN",
    "LATITUDE": 41.96487,
    "LONGITUDE": -78.63466,
    "WEBSITE": "http://www.amref.com",
    "OWNER": "AMERICAN REFINING GROUP INC",
    "OPERNAME": "AMERICAN REFINING GROUP INC",
    "CAPACITY": 11000,
    "US_RANK": 127,
    "CRUDE": 11000,
    "IMAGE": "https://drive.google.com/uc?id=1-u_4Yt6mGk7eTDzdt6qM4VzD86UGINJv"
  },
  {
    "OBJECTID": 29,
    "NAME": "EVANSTON",
    "ADDRESS": "2990 COUNTY ROAD 180",
    "CITY": "EVANSTON",
    "STATE": "WY",
    "TYPE": "VERY SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 26,
    "COUNTY": "UINTA",
    "LATITUDE": 41.26035,
    "LONGITUDE": -110.80691,
    "WEBSITE": "http://silvereagleenergy.com",
    "OWNER": "SILVER EAGLE REFINING INC",
    "OPERNAME": "SILVER EAGLE REFINING",
    "CAPACITY": 3000,
    "US_RANK": 136,
    "CRUDE": 3000,
    "IMAGE": "https://drive.google.com/uc?id=130BCixYXyfMaE4NmYf810WlwW5-NTLoy"
  },
  {
    "OBJECTID": 30,
    "NAME": "EWA BEACH",
    "ADDRESS": "91-325 KOMOHANA STREET",
    "CITY": "KAPOLEI",
    "STATE": "HI",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 260,
    "COUNTY": "HONOLULU",
    "LATITUDE": 21.30378,
    "LONGITUDE": -158.09246,
    "WEBSITE": "http://www.hawaiiindependentenergy.com",
    "OWNER": "PAR PETROLEUM INC",
    "OPERNAME": "HAWAII INDEPENDENT ENERGY LLC",
    "CAPACITY": 93500,
    "US_RANK": 68,
    "CRUDE": 93500,
    "IMAGE": "https://drive.google.com/uc?id=1unUzGosPqTylFEKcl4s5cv2R4pgbDjUD"
  },
  {
    "OBJECTID": 31,
    "NAME": "LOS ANGELES (WILMINGTON PLANT)",
    "ADDRESS": "2101 E PACIFIC COAST HIGHWAY",
    "CITY": "WILMINGTON",
    "STATE": "CA",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 520,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.79637,
    "LONGITUDE": -118.23297,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 94900,
    "US_RANK": 67,
    "CRUDE": 94900,
    "IMAGE": "https://drive.google.com/uc?id=1gnZ0ARi5K8GK5gYwg-X9Wq8l_AP3NG8P"
  },
  {
    "OBJECTID": 32,
    "NAME": "NORTH SALT LAKE",
    "ADDRESS": "333 W CENTER STREET",
    "CITY": "NORTH SALT LAKE",
    "STATE": "UT",
    "TYPE": "SMALL BUT MEDIUM COMPLEX REFINERY FOCUSED ON GASOLINE PRODUCTION",
    "STATUS": "IN SERVICE",
    "POPULATION": 146,
    "COUNTY": "DAVIS",
    "LATITUDE": 40.83864,
    "LONGITUDE": -111.92062,
    "WEBSITE": "http://www.bigwestoil.com",
    "OWNER": "FJ MANAGEMENT INC",
    "OPERNAME": "BIG WEST OIL CO",
    "CAPACITY": 30500,
    "US_RANK": 109,
    "CRUDE": 30500,
    "IMAGE": "https://drive.google.com/uc?id=1LKhZ9F15l0TZ5L8ua2rXl2QZJ40MoHw8"
  },
  {
    "OBJECTID": 33,
    "NAME": "HONOLULU",
    "ADDRESS": "91-480 MALAKOLE STREET",
    "CITY": "KAPOLEI",
    "STATE": "HI",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 203,
    "COUNTY": "HONOLULU",
    "LATITUDE": 21.30988,
    "LONGITUDE": -158.1118,
    "WEBSITE": "https://www.islandenergyservices.com",
    "OWNER": "ISLAND ENERGY SERVICES LLC",
    "OPERNAME": "ISLAND ENERGY SERVICES DOWNSTREAM",
    "CAPACITY": 54000,
    "US_RANK": 98,
    "CRUDE": 54000,
    "IMAGE": "https://drive.google.com/uc?id=1S38acLfwTOCNvlUmoYevvrRmD_hT3jor"
  },
  {
    "OBJECTID": 34,
    "NAME": "BATON ROUGE",
    "ADDRESS": "4045 SCENIC HIGHWAY",
    "CITY": "BATON ROUGE",
    "STATE": "LA",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1337,
    "COUNTY": "EAST BATON ROUGE",
    "LATITUDE": 30.4839,
    "LONGITUDE": -91.17958,
    "WEBSITE": "http://corporate.exxonmobil.com",
    "OWNER": "EXXON MOBIL CORP",
    "OPERNAME": "EXXONMOBIL REFINING & SUPPLY CO",
    "CAPACITY": 502500,
    "US_RANK": 4,
    "CRUDE": 502500,
    "IMAGE": "https://drive.google.com/uc?id=1rE5wpKPnN6yGNpSLPgNxpaTtYURgeF0G"
  },
  {
    "OBJECTID": 35,
    "NAME": "WILMINGTON",
    "ADDRESS": "1660 W. ANAHEIM STREET",
    "CITY": "WILMINGTON",
    "STATE": "CA",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 411,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.77309,
    "LONGITUDE": -118.28705,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 139000,
    "US_RANK": 54,
    "CRUDE": 139000,
    "IMAGE": "https://drive.google.com/uc?id=1Efw3bhjQmDYOkxr3oaJD2CVrks8dkQus"
  },
  {
    "OBJECTID": 36,
    "NAME": "TACOMA",
    "ADDRESS": "3001 MARSHALL AVENUE",
    "CITY": "TACOMA",
    "STATE": "WA",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 170,
    "COUNTY": "PIERCE",
    "LATITUDE": 47.25709,
    "LONGITUDE": -122.39626,
    "WEBSITE": "http://www.usor.com",
    "OWNER": "TRAILSTONE LP",
    "OPERNAME": "US OIL & REFINING CO",
    "CAPACITY": 40700,
    "US_RANK": 103,
    "CRUDE": 40700,
    "IMAGE": "https://drive.google.com/uc?id=1wovqPhfLq6Kmjfv5_PqdZB0Cv48L5EhE"
  },
  {
    "OBJECTID": 37,
    "NAME": "COTTON VALLEY",
    "ADDRESS": "1756 OLD HWY 7",
    "CITY": "COTTON VALLEY",
    "STATE": "LA",
    "TYPE": "SMALL LUBRICANTS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 42,
    "COUNTY": "WEBSTER",
    "LATITUDE": 32.79952,
    "LONGITUDE": -93.41136,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET LUBRICANTS CO LP",
    "CAPACITY": 13020,
    "US_RANK": 125,
    "CRUDE": 13020,
    "IMAGE": "https://drive.google.com/uc?id=1b5cFzlFN_zqqJpOdfan3BlA541MnzTS4"
  },
  {
    "OBJECTID": 38,
    "NAME": "GREAT FALLS",
    "ADDRESS": "1900 10TH STREET NE",
    "CITY": "GREAT FALLS",
    "STATE": "MT",
    "TYPE": "VERY SMALL BUT COMPLEX REFINERY CAPABLE OF PROCESSING THE HEAVIEST CRUDE",
    "STATUS": "IN SERVICE",
    "POPULATION": 95,
    "COUNTY": "CASCADE",
    "LATITUDE": 47.52363,
    "LONGITUDE": -111.29321,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET MONTANA REFINING LLC",
    "CAPACITY": 33600,
    "US_RANK": 108,
    "CRUDE": 24000,
    "IMAGE": "https://drive.google.com/uc?id=1Kkvq2lHpUvhFb2T5wJP3QMU8mc8gvMH6"
  },
  {
    "OBJECTID": 39,
    "NAME": "HOUSTON",
    "ADDRESS": "12000 LAWNDALE AVE",
    "CITY": "HOUSTON",
    "STATE": "TX",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 983,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.71373,
    "LONGITUDE": -95.23472,
    "WEBSITE": "http://www.lyondellbasell.com",
    "OWNER": "ACCESS INDUSTRIES",
    "OPERNAME": "HOUSTON REFINING LP",
    "CAPACITY": 263776,
    "US_RANK": 20,
    "CRUDE": 263776,
    "IMAGE": "https://drive.google.com/uc?id=1QHa-rQqSJIwsECbxVx-wc0L3CF6Mlquf"
  },
  {
    "OBJECTID": 40,
    "NAME": "BEAUMONT",
    "ADDRESS": "1795 BURT ST",
    "CITY": "BEAUMONT",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1166,
    "COUNTY": "JEFFERSON",
    "LATITUDE": 30.06365,
    "LONGITUDE": -94.0689,
    "WEBSITE": "http://cdn.exxonmobil.com",
    "OWNER": "EXXON MOBIL CORP",
    "OPERNAME": "EXXONMOBIL REFINING & SUPPLY CO",
    "CAPACITY": 362300,
    "US_RANK": 8,
    "CRUDE": 362300,
    "IMAGE": "https://drive.google.com/uc?id=1SXeWkYuN1Bi5bk5BvfDTFLrpanhwHJl6"
  },
  {
    "OBJECTID": 41,
    "NAME": "BENICIA",
    "ADDRESS": "3400 E SECOND ST",
    "CITY": "BENICIA",
    "STATE": "CA",
    "TYPE": "LARGE FUELS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 549,
    "COUNTY": "SOLANO",
    "LATITUDE": 38.07159,
    "LONGITUDE": -122.13795,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO CALIFORNIA",
    "CAPACITY": 145000,
    "US_RANK": 52,
    "CRUDE": 145000,
    "IMAGE": "https://drive.google.com/uc?id=1Iee9ly4t0NF94mW81WCUbaqQePR6v1yB"
  },
  {
    "OBJECTID": 42,
    "NAME": "PORT ALLEN",
    "ADDRESS": "1940 LOUISIANA HWY 1 NORTH",
    "CITY": "PORT ALLEN",
    "STATE": "LA",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 285,
    "COUNTY": "WEST BATON ROUGE",
    "LATITUDE": 30.47564,
    "LONGITUDE": -91.20631,
    "WEBSITE": "http://www.placidrefining.com",
    "OWNER": "PLACID OIL CO",
    "OPERNAME": "PLACID REFINING CO",
    "CAPACITY": 75000,
    "US_RANK": 81,
    "CRUDE": 75000,
    "IMAGE": "https://drive.google.com/uc?id=1ETUofsN0qHA2phlC1IzbvLkEgrhZZOTw"
  },
  {
    "OBJECTID": 43,
    "NAME": "TORRANCE",
    "ADDRESS": "3700 W 190TH STREET",
    "CITY": "TORRANCE",
    "STATE": "CA",
    "TYPE": "HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 800,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.85271,
    "LONGITUDE": -118.33026,
    "WEBSITE": "http://corporate.exxonmobil.com",
    "OWNER": "PBF ENERGY CO LLC",
    "OPERNAME": "TORRANCE REFINING CO LLC",
    "CAPACITY": 150900,
    "US_RANK": 49,
    "CRUDE": 150900,
    "IMAGE": "https://drive.google.com/uc?id=1lTFB0LbO3iQ1veVj_TeUrNIS57YGgNqI"
  },
  {
    "OBJECTID": 44,
    "NAME": "BAKERSFIELD",
    "ADDRESS": "7724 E PANAMA LN",
    "CITY": "BAKERSFIELD",
    "STATE": "CA",
    "TYPE": "SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 110,
    "COUNTY": "KERN",
    "LATITUDE": 35.29459,
    "LONGITUDE": -118.91804,
    "WEBSITE": "http://www.kernoil.com",
    "OWNER": "KERN OIL & REFINING CO",
    "OPERNAME": "KERN OIL & REFINING CO",
    "CAPACITY": 26000,
    "US_RANK": 112,
    "CRUDE": 26000,
    "IMAGE": "https://drive.google.com/uc?id=1lBtC-vlGu-8yko1UIgCFDJ3k80grLkR0"
  },
  {
    "OBJECTID": 45,
    "NAME": "LINDEN",
    "ADDRESS": "1400 PARK AVE SOUTH",
    "CITY": "LINDEN",
    "STATE": "NJ",
    "TYPE": "LARGE COMPLEX REFINERY COLOCATED WITH PETROCHEMICALS",
    "STATUS": "IN SERVICE",
    "POPULATION": 830,
    "COUNTY": "UNION",
    "LATITUDE": 40.6324,
    "LONGITUDE": -74.22303,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 241000,
    "US_RANK": 25,
    "CRUDE": 241000,
    "IMAGE": "https://drive.google.com/uc?id=1IhX1QC8zq8j1AuitqbOsCq3ACfMx_CaA"
  },
  {
    "OBJECTID": 46,
    "NAME": "SWEENY",
    "ADDRESS": "SOUTHWEST OF THE INTERSECTION OF FM 524 AND HWY 35",
    "CITY": "OLD OCEAN",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 923,
    "COUNTY": "BRAZORIA",
    "LATITUDE": 29.07292,
    "LONGITUDE": -95.74694,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 247000,
    "US_RANK": 23,
    "CRUDE": 247000,
    "IMAGE": "https://drive.google.com/uc?id=1BoL7s5pQUEHqobYmqUrN17Ul-mPA0176"
  },
  {
    "OBJECTID": 47,
    "NAME": "SANDERSVILLE",
    "ADDRESS": "177 HANEY RD HWY 11 N (2 MI N OF SANDERSVILLE)",
    "CITY": "HEIDELBERG",
    "STATE": "MS",
    "TYPE": "SMALL ASPHALT REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 40,
    "COUNTY": "JONES",
    "LATITUDE": 31.81706,
    "LONGITUDE": -89.00875,
    "WEBSITE": "http://www.huntrefining.com",
    "OWNER": "HUNT CONSLD INC",
    "OPERNAME": "HUNT SOUTHLAND REFINING CO",
    "CAPACITY": 11000,
    "US_RANK": 126,
    "CRUDE": 11000,
    "IMAGE": "https://drive.google.com/uc?id=1LCKkmNspnEyiz3C-sQgH1tQLf2aLK5Sc"
  },
  {
    "OBJECTID": 48,
    "NAME": "NAVAJO",
    "ADDRESS": "501 E MAIN ST",
    "CITY": "ARTESIA",
    "STATE": "NM",
    "TYPE": "MEDIUM SIZED HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 330,
    "COUNTY": "EDDY",
    "LATITUDE": 32.84693,
    "LONGITUDE": -104.39327,
    "WEBSITE": "http://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER NAVAJO REFINING LLC",
    "CAPACITY": 98000,
    "US_RANK": 65,
    "CRUDE": 98000,
    "IMAGE": "https://drive.google.com/uc?id=1V89nQeRQThpBTbxoOK0rE_dXPuB_9DGz"
  },
  {
    "OBJECTID": 49,
    "NAME": "SARALAND",
    "ADDRESS": "400 INDUSTRIAL PARKWAY EXTENSION EAST",
    "CITY": "SARALAND",
    "STATE": "AL",
    "TYPE": "SMALL / MEDIUM SIZED SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 165,
    "COUNTY": "MOBILE",
    "LATITUDE": 30.78914,
    "LONGITUDE": -88.05573,
    "WEBSITE": "http://www.shell.com",
    "OWNER": "ROYAL DUTCH/SHELL GROUP",
    "OPERNAME": "SHELL CHEMICAL LP",
    "CAPACITY": 91575,
    "US_RANK": 70,
    "CRUDE": 91575,
    "IMAGE": "https://drive.google.com/uc?id=1T93uGwcgRKcGyELd8shKxtrdeVVN9fIw"
  },
  {
    "OBJECTID": 50,
    "NAME": "SALT LAKE CITY",
    "ADDRESS": "2351 NORTH 1100 WEST",
    "CITY": "SALT LAKE CITY",
    "STATE": "UT",
    "TYPE": "SMALL COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 301,
    "COUNTY": "SALT LAKE",
    "LATITUDE": 40.8259,
    "LONGITUDE": -111.92327,
    "WEBSITE": "https://www.chevron.com/",
    "OWNER": "CHEVRON CORP",
    "OPERNAME": "CHEVRON USA INC",
    "CAPACITY": 54500,
    "US_RANK": 97,
    "CRUDE": 54500,
    "IMAGE": "https://drive.google.com/uc?id=1cYqssNSSWL_uR-ZVTwEsls4YVy2yPDG1"
  },
  {
    "OBJECTID": 51,
    "NAME": "FERNDALE",
    "ADDRESS": "3901 UNICK ROAD",
    "CITY": "FERNDALE",
    "STATE": "WA",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 406,
    "COUNTY": "WHATCOM",
    "LATITUDE": 48.82973,
    "LONGITUDE": -122.69437,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 101000,
    "US_RANK": 64,
    "CRUDE": 101000,
    "IMAGE": "https://drive.google.com/uc?id=1SxWloW24gMPxpdbMYUn1THIVXVudkskd"
  },
  {
    "OBJECTID": 52,
    "NAME": "CHEYENNE",
    "ADDRESS": "2700 EAST 5TH STREET",
    "CITY": "CHEYENNE",
    "STATE": "WY",
    "TYPE": "SMALL COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 300,
    "COUNTY": "LARAMIE",
    "LATITUDE": 41.12768,
    "LONGITUDE": -104.78969,
    "WEBSITE": "http://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER CHEYENNE REFINING LLC",
    "CAPACITY": 47000,
    "US_RANK": 99,
    "CRUDE": 47000,
    "IMAGE": "https://drive.google.com/uc?id=1vr5D3VcwrO6Q16H015D1_neG66-n1V31"
  },
  {
    "OBJECTID": 53,
    "NAME": "EL DORADO",
    "ADDRESS": "1000 MCHENRY ST",
    "CITY": "EL DORADO",
    "STATE": "AR",
    "TYPE": "SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 327,
    "COUNTY": "UNION",
    "LATITUDE": 33.19927,
    "LONGITUDE": -92.67513,
    "WEBSITE": "http://www.lionoil.com",
    "OWNER": "DELEK GROUP LTD",
    "OPERNAME": "LION OIL CO",
    "CAPACITY": 83000,
    "US_RANK": 79,
    "CRUDE": 83000,
    "IMAGE": "https://drive.google.com/uc?id=11PZ81uTbxiU34gLiuECMQ726kTZ5QNtW"
  },
  {
    "OBJECTID": 54,
    "NAME": "VICKSBURG",
    "ADDRESS": "2611 HAINING ROAD",
    "CITY": "VICKSBURG",
    "STATE": "MS",
    "TYPE": "SMALL SCALE SPECIALIST NAPHTHENIC PROCESS OIL PRODUCER",
    "STATUS": "IN SERVICE",
    "POPULATION": 180,
    "COUNTY": "WARREN",
    "LATITUDE": 32.38658,
    "LONGITUDE": -90.90825,
    "WEBSITE": "http://ergon.com",
    "OWNER": "ERGON INC",
    "OPERNAME": "ERGON REFINING INC",
    "CAPACITY": 26500,
    "US_RANK": 111,
    "CRUDE": 26500,
    "IMAGE": "https://drive.google.com/uc?id=15U1Chzon57hUM1oK2zoLmmvtrSEPJhDA"
  },
  {
    "OBJECTID": 55,
    "NAME": "SILSBEE",
    "ADDRESS": "7752 WEST FM 418",
    "CITY": "SILSBEE",
    "STATE": "TX",
    "TYPE": "SMALL AROMATICS PRODUCER",
    "STATUS": "IN SERVICE",
    "POPULATION": 125,
    "COUNTY": "HARDIN",
    "LATITUDE": 30.39826,
    "LONGITUDE": -94.22855,
    "WEBSITE": "http://www.southhamptonr.com",
    "OWNER": "TEXAS OIL & CHEMICAL CO",
    "OPERNAME": "SOUTH HAMPTON RESOURCES INC",
    "CAPACITY": 0,
    "US_RANK": 140,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1BKDmVGYexDzZN2IOrsNR8VJJR-gjl9UL"
  },
  {
    "OBJECTID": 56,
    "NAME": "LEMONT",
    "ADDRESS": "135TH STREET AND NEW AVE",
    "CITY": "LEMONT",
    "STATE": "IL",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 513,
    "COUNTY": "WILL",
    "LATITUDE": 41.65374,
    "LONGITUDE": -88.04839,
    "WEBSITE": "http://www.citgo.com",
    "OWNER": "PDV AMERICA INC",
    "OPERNAME": "PDV MIDWEST REFINING LLC",
    "CAPACITY": 175940,
    "US_RANK": 42,
    "CRUDE": 175940,
    "IMAGE": "https://drive.google.com/uc?id=1ln7PMsgMtwxvGliageeYW8K38qa52w8Z"
  },
  {
    "OBJECTID": 57,
    "NAME": "BILLINGS",
    "ADDRESS": "401 S 23RD STREET",
    "CITY": "BILLINGS",
    "STATE": "MT",
    "TYPE": "SMALL BUT COMPLEX REFINERY WITH A HIGH CLEAN PRODUCT YIELD",
    "STATUS": "IN SERVICE",
    "POPULATION": 296,
    "COUNTY": "YELLOWSTONE",
    "LATITUDE": 45.78061,
    "LONGITUDE": -108.48972,
    "WEBSITE": "http://www.conocophillips.com/",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 60000,
    "US_RANK": 93,
    "CRUDE": 60000,
    "IMAGE": "https://drive.google.com/uc?id=1YrJHJFnbtX7TyB0iyDfn4SK4W3Ez3NQk"
  },
  {
    "OBJECTID": 58,
    "NAME": "WARREN",
    "ADDRESS": "15 BRADLEY STREET",
    "CITY": "WARREN",
    "STATE": "PA",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 643,
    "COUNTY": "WARREN",
    "LATITUDE": 41.8297,
    "LONGITUDE": -79.12742,
    "WEBSITE": "http://www.urc.com",
    "OWNER": "RED APPLE GROUP INC",
    "OPERNAME": "UNITED REFINING CO",
    "CAPACITY": 65000,
    "US_RANK": 90,
    "CRUDE": 65000,
    "IMAGE": "https://drive.google.com/uc?id=1M1ydWCZm8DkoAbjRBta5Hmme6Lf572hF"
  },
  {
    "OBJECTID": 59,
    "NAME": "ANACORTES",
    "ADDRESS": "8505 S. TEXAS RD",
    "CITY": "ANACORTES",
    "STATE": "WA",
    "TYPE": "MEDIUM TO LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 477,
    "COUNTY": "SKAGIT",
    "LATITUDE": 48.47182,
    "LONGITUDE": -122.55912,
    "WEBSITE": "http://www.shell.us",
    "OWNER": "ROYAL DUTCH/SHELL GROUP",
    "OPERNAME": "SHELL OIL PRODUCTS US",
    "CAPACITY": 145000,
    "US_RANK": 53,
    "CRUDE": 145000,
    "IMAGE": "https://drive.google.com/uc?id=1dEkPMV3LPIjwNHiDbLZtITtbf0StbHzs"
  },
  {
    "OBJECTID": 60,
    "NAME": "NORCO",
    "ADDRESS": "15536 RIVER RD",
    "CITY": "NORCO",
    "STATE": "LA",
    "TYPE": "LARGE COMPLEX REFINERY WITH A HIGH GASOLINE YIELD",
    "STATUS": "IN SERVICE",
    "POPULATION": 1200,
    "COUNTY": "ST. CHARLES",
    "LATITUDE": 30.00314,
    "LONGITUDE": -90.40214,
    "WEBSITE": "https://www.shell.us",
    "OWNER": "ROYAL DUTCH SHELL",
    "OPERNAME": "SHELL OIL PRODUCTS US (REFINING)",
    "CAPACITY": 225800,
    "US_RANK": 30,
    "CRUDE": 225800,
    "IMAGE": "https://drive.google.com/uc?id=1chjkDAaFhE5l4TsVJWJwj3t52GkUMFbv"
  },
  {
    "OBJECTID": 61,
    "NAME": "TUSCALOOSA",
    "ADDRESS": "1855 FAIRLAWN RD",
    "CITY": "TUSCALOOSA",
    "STATE": "AL",
    "TYPE": "SMALL / MEDIUM SIZED REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 259,
    "COUNTY": "TUSCALOOSA",
    "LATITUDE": 33.2005,
    "LONGITUDE": -87.60783,
    "WEBSITE": "http://www.huntrefining.com",
    "OWNER": "HUNT CONSLD INC",
    "OPERNAME": "HUNT REFINING CO",
    "CAPACITY": 36000,
    "US_RANK": 106,
    "CRUDE": 36000,
    "IMAGE": "https://drive.google.com/uc?id=1GrYyUrwXRwRgpKA0PpKS6AmykJOrk2tk"
  },
  {
    "OBJECTID": 62,
    "NAME": "CORPUS CHRISTI",
    "ADDRESS": "1802 NUECES BAY BLVD.",
    "CITY": "CORPUS CHRISTI",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 665,
    "COUNTY": "NUECES",
    "LATITUDE": 27.80941,
    "LONGITUDE": -97.42639,
    "WEBSITE": "http://citgorefining.com/",
    "OWNER": "PDV AMERICA INC",
    "OPERNAME": "CITGO REFINING & CHEMICAL INC",
    "CAPACITY": 157500,
    "US_RANK": 46,
    "CRUDE": 157500,
    "IMAGE": "https://drive.google.com/uc?id=1o3-Rxrm2meZ8MmNLW0q8egyTXZsdh3p5"
  },
  {
    "OBJECTID": 63,
    "NAME": "WOODS CROSS",
    "ADDRESS": "393 SOUTH 800 WEST",
    "CITY": "WOODS CROSS",
    "STATE": "UT",
    "TYPE": "SMALL BUT HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 188,
    "COUNTY": "DAVIS",
    "LATITUDE": 40.887,
    "LONGITUDE": -111.90389,
    "WEBSITE": "http://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER WOODS CROSS REFINING L",
    "CAPACITY": 39330,
    "US_RANK": 104,
    "CRUDE": 39330,
    "IMAGE": "https://drive.google.com/uc?id=1SXwfy06sP17PDMIIGyG2aQwXf9UwVf57"
  },
  {
    "OBJECTID": 64,
    "NAME": "PORT ARTHUR",
    "ADDRESS": "1801 S GULFWAY DRIVE",
    "CITY": "PORT ARTHUR",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 840,
    "COUNTY": "JEFFERSON",
    "LATITUDE": 29.86055,
    "LONGITUDE": -93.96562,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "PREMCOR REFINING GROUP INC",
    "CAPACITY": 335000,
    "US_RANK": 11,
    "CRUDE": 335000,
    "IMAGE": "https://drive.google.com/uc?id=16c2pYHsYjsIaNzgxqElfjC9jLUigSXan"
  },
  {
    "OBJECTID": 65,
    "NAME": "TOLEDO",
    "ADDRESS": "1819 WOODVILLE ROAD",
    "CITY": "OREGON",
    "STATE": "OH",
    "TYPE": "HIGH CONVERSION LIGHT/SWEET REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 525,
    "COUNTY": "LUCAS",
    "LATITUDE": 41.6328,
    "LONGITUDE": -83.5019,
    "WEBSITE": "http://www.pbfenergy.com",
    "OWNER": "PBF ENERGY CO LLC",
    "OPERNAME": "TOLEDO REFINING CO LLC",
    "CAPACITY": 160000,
    "US_RANK": 45,
    "CRUDE": 160000,
    "IMAGE": "https://drive.google.com/uc?id=1DmuAkzRb7zmD5ClaAdMBzkae0J-6JEMi"
  },
  {
    "OBJECTID": 66,
    "NAME": "BELLE CHASSE",
    "ADDRESS": "15551 HWY 23",
    "CITY": "BELLE CHASSE",
    "STATE": "LA",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 354,
    "COUNTY": "PLAQUEMINES",
    "LATITUDE": 29.68239,
    "LONGITUDE": -89.97501,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 247000,
    "US_RANK": 22,
    "CRUDE": 247000,
    "IMAGE": "https://drive.google.com/uc?id=1FwaNjshvSyqOluomNRLtU-C2kSm0dfFF"
  },
  {
    "OBJECTID": 67,
    "NAME": "KROTZ SPRINGS",
    "ADDRESS": "356 S LEVEE ROAD",
    "CITY": "KROTZ SPRINGS",
    "STATE": "LA",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 208,
    "COUNTY": "ST. LANDRY",
    "LATITUDE": 30.5256,
    "LONGITUDE": -91.75003,
    "WEBSITE": "http://www.alonusa.com",
    "OWNER": "ALON ISRAEL OIL COMPANY LTD",
    "OPERNAME": "ALON REFINING KROTZ SPRINGS INC",
    "CAPACITY": 80000,
    "US_RANK": 80,
    "CRUDE": 80000,
    "IMAGE": "https://drive.google.com/uc?id=1MqNHZhr-aZdOojk-1TVYF9eY-UpJX6Vv"
  },
  {
    "OBJECTID": 68,
    "NAME": "EL SEGUNDO",
    "ADDRESS": "324 W EL SEGUNDO BLVD",
    "CITY": "EL SEGUNDO",
    "STATE": "CA",
    "TYPE": "LARGE FUELS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1200,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.91022,
    "LONGITUDE": -118.40949,
    "WEBSITE": "https://www.chevron.com/",
    "OWNER": "CHEVRON CORP",
    "OPERNAME": "CHEVRON USA INC",
    "CAPACITY": 269000,
    "US_RANK": 19,
    "CRUDE": 269000,
    "IMAGE": "https://drive.google.com/uc?id=1R7hMgNLECqRtmtOL9yas63fAr2aD19Yw"
  },
  {
    "OBJECTID": 69,
    "NAME": "JOLIET",
    "ADDRESS": "25915 SE FRONTAGE ROAD",
    "CITY": "CHANNAHON",
    "STATE": "IL",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 576,
    "COUNTY": "WILL",
    "LATITUDE": 41.41383,
    "LONGITUDE": -88.18346,
    "WEBSITE": "http://corporate.exxonmobil.com",
    "OWNER": "EXXON MOBIL CORP",
    "OPERNAME": "EXXONMOBIL REFINING & SUPPLY CO",
    "CAPACITY": 238600,
    "US_RANK": 26,
    "CRUDE": 238600,
    "IMAGE": "https://drive.google.com/uc?id=1MxvHrlYfLpCK7b1lMc0QPbjHl1q_pEvj"
  },
  {
    "OBJECTID": 70,
    "NAME": "PHILADELPHIA (PES REFINING COMPLEX)",
    "ADDRESS": "3144 PASSYUNK AVE",
    "CITY": "PHILADELPHIA",
    "STATE": "PA",
    "TYPE": "LARGE MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 830,
    "COUNTY": "PHILADELPHIA",
    "LATITUDE": 39.90319,
    "LONGITUDE": -75.20799,
    "WEBSITE": "http://www.pes-companies.com",
    "OWNER": "CARLYLE GROUP",
    "OPERNAME": "PHILADELPHIA ENERGY SOLUTIONS",
    "CAPACITY": 310000,
    "US_RANK": 13,
    "CRUDE": 310000,
    "IMAGE": "https://drive.google.com/uc?id=1iPKqBPIDfD7A3bcMe8dthSzb6XIRt1Ap"
  },
  {
    "OBJECTID": 71,
    "NAME": "PONCA CITY",
    "ADDRESS": "1000 S PINE STREET",
    "CITY": "PONCA CITY",
    "STATE": "OK",
    "TYPE": "LARGE HIGH-CONVERSION REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 850,
    "COUNTY": "KAY",
    "LATITUDE": 36.68193,
    "LONGITUDE": -97.09105,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 200000,
    "US_RANK": 34,
    "CRUDE": 200000,
    "IMAGE": "https://drive.google.com/uc?id=1D85Nmtv4tsOw5lA6Pg2sSHbsgB003BDU"
  },
  {
    "OBJECTID": 72,
    "NAME": "PASCAGOULA",
    "ADDRESS": "250 INDUSTRIAL ROAD",
    "CITY": "PASCAGOULA",
    "STATE": "MS",
    "TYPE": "LARGE AND VERY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1610,
    "COUNTY": "JACKSON",
    "LATITUDE": 30.34345,
    "LONGITUDE": -88.48672,
    "WEBSITE": "https://www.chevron.com/",
    "OWNER": "CHEVRON CORP",
    "OPERNAME": "CHEVRON USA INC",
    "CAPACITY": 340000,
    "US_RANK": 9,
    "CRUDE": 340000,
    "IMAGE": "https://drive.google.com/uc?id=1m7wjylPxebLBnsiKlwes_NOGk1P9uPfK"
  },
  {
    "OBJECTID": 73,
    "NAME": "VALDEZ",
    "ADDRESS": "2.5 MILE DAYVILLE ROAD",
    "CITY": "VALDEZ",
    "STATE": "AK",
    "TYPE": "SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 38,
    "COUNTY": "VALDEZ-CORDOVA",
    "LATITUDE": 61.08396,
    "LONGITUDE": -146.25057,
    "WEBSITE": "http://www.petrostar.com",
    "OWNER": "ARCTIC SLOPE REGIONAL CORP",
    "OPERNAME": "PETRO STAR INC",
    "CAPACITY": 55000,
    "US_RANK": 96,
    "CRUDE": 55000,
    "IMAGE": "https://drive.google.com/uc?id=1EChu-v6gVLOpzB6D8JxV6GHoQxTcil2t"
  },
  {
    "OBJECTID": 74,
    "NAME": "DELAWARE CITY",
    "ADDRESS": "4550 WRANGLE HILL ROAD",
    "CITY": "DELAWARE CITY",
    "STATE": "DE",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 600,
    "COUNTY": "NEWCASTLE",
    "LATITUDE": 39.5873,
    "LONGITUDE": -75.63058,
    "WEBSITE": "http://www.pbfenergy.com",
    "OWNER": "PBF ENERGY CO LLC",
    "OPERNAME": "DELAWARE CITY REFINING CO LLC",
    "CAPACITY": 182200,
    "US_RANK": 40,
    "CRUDE": 182200,
    "IMAGE": "https://drive.google.com/uc?id=14ZLXlcoNbAvcLvOBIiC1T9mk_a1kWFYE"
  },
  {
    "OBJECTID": 75,
    "NAME": "SOUTH GATE",
    "ADDRESS": "9302 GARFIELD AVENUE",
    "CITY": "SOUTH GATE",
    "STATE": "CA",
    "TYPE": "VERY SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 62,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.9463,
    "LONGITUDE": -118.16704,
    "WEBSITE": "http://www.lundaythagard.com",
    "OWNER": "WORLD OIL CO",
    "OPERNAME": "LUNDAY THAGARD CO",
    "CAPACITY": 8500,
    "US_RANK": 129,
    "CRUDE": 8500,
    "IMAGE": "https://drive.google.com/uc?id=1pkrFX5mPOg4j1QKFWIUa45NneJAinSye"
  },
  {
    "OBJECTID": 76,
    "NAME": "SALT LAKE CITY",
    "ADDRESS": "474 WEST 900 NORTH",
    "CITY": "SALT LAKE CITY",
    "STATE": "UT",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 260,
    "COUNTY": "SALT LAKE",
    "LATITUDE": 40.79395,
    "LONGITUDE": -111.90812,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 63000,
    "US_RANK": 91,
    "CRUDE": 57500,
    "IMAGE": "https://drive.google.com/uc?id=1mxTAmysFdStC1_a6ckoRSQdgD1yngKP_"
  },
  {
    "OBJECTID": 77,
    "NAME": "EL PASO",
    "ADDRESS": "6500 TROWBRIDGE DRIVE/212 N CLARK DR",
    "CITY": "EL PASO",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 440,
    "COUNTY": "EL PASO",
    "LATITUDE": 31.76949,
    "LONGITUDE": -106.4036,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 122000,
    "US_RANK": 57,
    "CRUDE": 122000,
    "IMAGE": "https://drive.google.com/uc?id=1eqjVtfLQQo3-Gy64h9YyAuAKidYMecUy"
  },
  {
    "OBJECTID": 78,
    "NAME": "CORPUS CHRISTI EAST AND WEST",
    "ADDRESS": "1607 NUECES BAY BLVD",
    "CITY": "CORPUS CHRISTI",
    "STATE": "TX",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 22,
    "COUNTY": "NUECES",
    "LATITUDE": 27.80624,
    "LONGITUDE": -97.42306,
    "WEBSITE": "http://www.fhr.com",
    "OWNER": "KOCH INDUSTRIES INC",
    "OPERNAME": "FLINT HILLS RESOURCES LP",
    "CAPACITY": 296470,
    "US_RANK": 14,
    "CRUDE": 296470,
    "IMAGE": "https://drive.google.com/uc?id=1VJT0XldpoJ1q7ADFYeGkrG28WQRW7tMS"
  },
  {
    "OBJECTID": 79,
    "NAME": "ANACORTES",
    "ADDRESS": "WEST MARCH'S POINT ROAD",
    "CITY": "ANACORTES",
    "STATE": "WA",
    "TYPE": "MEDIUM TO LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 390,
    "COUNTY": "SKAGIT",
    "LATITUDE": 48.49396568,
    "LONGITUDE": -122.5659765,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 120000,
    "US_RANK": 59,
    "CRUDE": 120000,
    "IMAGE": "https://drive.google.com/uc?id=1QwxxGJny3s1a5rCyy2KVH0keh8ZG87z0"
  },
  {
    "OBJECTID": 80,
    "NAME": "GARYVILLE",
    "ADDRESS": "4663 WEST AIRLINE HWY",
    "CITY": "GARYVILLE",
    "STATE": "LA",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 930,
    "COUNTY": "ST. JOHN THE BAPTIST",
    "LATITUDE": 30.06129,
    "LONGITUDE": -90.59639,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 543000,
    "US_RANK": 3,
    "CRUDE": 543000,
    "IMAGE": "https://drive.google.com/uc?id=1jU55u1Eh-2hfHJJDEzYfAu6DmnTCNgJj"
  },
  {
    "OBJECTID": 81,
    "NAME": "NEW CASTLE",
    "ADDRESS": "740 WEST MAIN STREET",
    "CITY": "NEWCASTLE",
    "STATE": "WY",
    "TYPE": "VERY SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 94,
    "COUNTY": "WESTON",
    "LATITUDE": 43.84958,
    "LONGITUDE": -104.21464,
    "WEBSITE": "http://www.parpacific.com",
    "OWNER": "PAR PETROLEUM INC",
    "OPERNAME": "HERMES CONSOLIDATED LLC",
    "CAPACITY": 18000,
    "US_RANK": 120,
    "CRUDE": 18000,
    "IMAGE": "https://drive.google.com/uc?id=1roud8qw3B04AthWi0ApeERA4G1O_Uo0b"
  },
  {
    "OBJECTID": 82,
    "NAME": "BORGER",
    "ADDRESS": "SPUR 119 NORTH",
    "CITY": "BORGER",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED REFINERY INCLUDES AN NGL FRACTIONATION FACILITY",
    "STATUS": "IN SERVICE",
    "POPULATION": 709,
    "COUNTY": "HUTCHINSON",
    "LATITUDE": 35.69769,
    "LONGITUDE": -101.36159,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "WRB REFINING LP (PHILLIPS66/CENOVUS)",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 146000,
    "US_RANK": 51,
    "CRUDE": 146000,
    "IMAGE": "https://drive.google.com/uc?id=1w1ZsGvZTItBXACnudzcFcsSpyq5WQKin"
  },
  {
    "OBJECTID": 83,
    "NAME": "LIMA",
    "ADDRESS": "1150 SOUTH METCALF STREET",
    "CITY": "LIMA",
    "STATE": "OH",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 393,
    "COUNTY": "ALLEN",
    "LATITUDE": 40.71772,
    "LONGITUDE": -84.12643,
    "WEBSITE": "http://www.huskyenergy.com",
    "OWNER": "HUSKY ENERGY INC",
    "OPERNAME": "LIMA REFINING COMPANY",
    "CAPACITY": 177000,
    "US_RANK": 41,
    "CRUDE": 177000,
    "IMAGE": "https://drive.google.com/uc?id=1K-DIUVBgw1wcNPOdxzoghcLojeO5qadY"
  },
  {
    "OBJECTID": 84,
    "NAME": "KENAI",
    "ADDRESS": "54741 TESORO ROAD",
    "CITY": "KENAI",
    "STATE": "AK",
    "TYPE": "MEDIUM SIZED FUELS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 230,
    "COUNTY": "KENAI PENINSULA",
    "LATITUDE": 60.68387,
    "LONGITUDE": -151.36605,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 72000,
    "US_RANK": 85,
    "CRUDE": 62700,
    "IMAGE": "https://drive.google.com/uc?id=1XnOkXM14BmH5dd8BHxcg1VVVlglrSFfD"
  },
  {
    "OBJECTID": 85,
    "NAME": "MERAUX",
    "ADDRESS": "2500 EAST ST. BERNARD HWY",
    "CITY": "MERAUX",
    "STATE": "LA",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 274,
    "COUNTY": "ST. BERNARD",
    "LATITUDE": 29.93542,
    "LONGITUDE": -89.93908,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO ENERGY CORPORATION",
    "CAPACITY": 125000,
    "US_RANK": 56,
    "CRUDE": 125000,
    "IMAGE": "https://drive.google.com/uc?id=1im5ia3ukLdbdBWYx1dt_N1cISGFadqp_"
  },
  {
    "OBJECTID": 86,
    "NAME": "WYNNEWOOD",
    "ADDRESS": "906 S. POWELL",
    "CITY": "WYNNEWOOD",
    "STATE": "OK",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY WITH BOTH FCC & HYDROCRACKER",
    "STATUS": "IN SERVICE",
    "POPULATION": 260,
    "COUNTY": "GARVIN",
    "LATITUDE": 34.63057,
    "LONGITUDE": -97.16788,
    "WEBSITE": "http://www.cvrrefining.com",
    "OWNER": "CVR ENERGY",
    "OPERNAME": "WYNNEWOOD REFINING CO",
    "CAPACITY": 70000,
    "US_RANK": 88,
    "CRUDE": 70000,
    "IMAGE": "https://drive.google.com/uc?id=1mnrAyPiJFOhdys5NATOcsHGKLzkeq7Nu"
  },
  {
    "OBJECTID": 87,
    "NAME": "SAINT PAUL",
    "ADDRESS": "12555 CLARK RD",
    "CITY": "ROSEMOUNT",
    "STATE": "MN",
    "TYPE": "LARGE HIGHLY COMPLEX REFINERY THAT PROCESSES VERY HEAVY CRUDES",
    "STATUS": "IN SERVICE",
    "POPULATION": 918,
    "COUNTY": "DAKOTA",
    "LATITUDE": 44.76598,
    "LONGITUDE": -93.04178,
    "WEBSITE": "http://www.fhr.com",
    "OWNER": "KOCH INDUSTRIES INC",
    "OPERNAME": "FLINT HILLS RESOURCES LP",
    "CAPACITY": 290000,
    "US_RANK": 16,
    "CRUDE": 290000,
    "IMAGE": "https://drive.google.com/uc?id=1kgJfSSldlT5A0jemNcX8Yf5GxDIPEHrd"
  },
  {
    "OBJECTID": 88,
    "NAME": "LAKE CHARLES",
    "ADDRESS": "4359 WEST TANK FARM RD",
    "CITY": "LAKE CHARLES",
    "STATE": "LA",
    "TYPE": "SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 38,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.13371,
    "LONGITUDE": -93.32054,
    "WEBSITE": "http://www.calcasieurefining.com",
    "OWNER": "TRANSWORLD OIL USA INC",
    "OPERNAME": "CALCASIEU REFINING CO",
    "CAPACITY": 104000,
    "US_RANK": 62,
    "CRUDE": 104000,
    "IMAGE": "https://drive.google.com/uc?id=1m3PAuwSHILu0mcrPIc2RkEdqYe8E4OSQ"
  },
  {
    "OBJECTID": 89,
    "NAME": "PORT ARTHUR",
    "ADDRESS": "HWY 366 AND 32ND STREET",
    "CITY": "PORT ARTHUR",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 500,
    "COUNTY": "JEFFERSON",
    "LATITUDE": 29.96016,
    "LONGITUDE": -93.88862,
    "WEBSITE": "http://www.totalpetrochemicalsusa.com",
    "OWNER": "TOTAL SA",
    "OPERNAME": "TOTAL PETROCHEMICALS & REFINING USA",
    "CAPACITY": 225500,
    "US_RANK": 31,
    "CRUDE": 225500,
    "IMAGE": "https://drive.google.com/uc?id=1f7Vzq2hymawTGwxOyiDA8ktfMfh6J-xW"
  },
  {
    "OBJECTID": 90,
    "NAME": "CANTON",
    "ADDRESS": "2408 GAMBRINUS AVE SW",
    "CITY": "CANTON",
    "STATE": "OH",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 361,
    "COUNTY": "STARK",
    "LATITUDE": 40.77343,
    "LONGITUDE": -81.41391,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 93000,
    "US_RANK": 69,
    "CRUDE": 93000,
    "IMAGE": "https://drive.google.com/uc?id=1w_G8mt9Wz5HHRFAnbOwfXhYaZuJmEDD3"
  },
  {
    "OBJECTID": 91,
    "NAME": "GALLUP",
    "ADDRESS": "92 GIANT CROSSING ROAD, I-40 AT EXIT 39",
    "CITY": "JAMESTOWN",
    "STATE": "NM",
    "TYPE": "SMALL REFINERY WITH SOME CRACKING CAPABILITY",
    "STATUS": "IN SERVICE",
    "POPULATION": 220,
    "COUNTY": "MCKINLEY",
    "LATITUDE": 35.48885,
    "LONGITUDE": -108.42582,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORPORATION",
    "OPERNAME": "MARATHON PETROLEUM CORPORATION",
    "CAPACITY": 25500,
    "US_RANK": 113,
    "CRUDE": 25500,
    "IMAGE": "https://drive.google.com/uc?id=1Zo2g7hiftfeAe9ZvfN14m5nd1MmD1FzS"
  },
  {
    "OBJECTID": 92,
    "NAME": "ARDMORE",
    "ADDRESS": "1 VALERO WAY",
    "CITY": "ARDMORE",
    "STATE": "OK",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY CAPABLE OF PROCESSING A RANGE OF CRUDE OILS",
    "STATUS": "IN SERVICE",
    "POPULATION": 320,
    "COUNTY": "CARTER",
    "LATITUDE": 34.20492,
    "LONGITUDE": -97.10442,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO OKLAHOMA",
    "CAPACITY": 86000,
    "US_RANK": 72,
    "CRUDE": 86000,
    "IMAGE": "https://drive.google.com/uc?id=1Kacuh-5TaE_JF3M06NbiDZEZK7fOJQ23"
  },
  {
    "OBJECTID": 93,
    "NAME": "PORT ARTHUR",
    "ADDRESS": "2555 SAVANNAH AVENUE",
    "CITY": "PORT ARTHUR",
    "STATE": "TX",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1050,
    "COUNTY": "JEFFERSON",
    "LATITUDE": 29.88301,
    "LONGITUDE": -93.95994,
    "WEBSITE": "https://www.motiva.com/",
    "OWNER": "MOTIVA ENTERPRISES LLC",
    "OPERNAME": "MOTIVA ENTERPRISES LLC",
    "CAPACITY": 603000,
    "US_RANK": 1,
    "CRUDE": 603000,
    "IMAGE": "https://drive.google.com/uc?id=1wS0pdNKesmKBC7gj2sZoNxbWV2c-jev9"
  },
  {
    "OBJECTID": 94,
    "NAME": "NORCO",
    "ADDRESS": "14902 RIVER RD",
    "CITY": "NORCO",
    "STATE": "LA",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 530,
    "COUNTY": "ST. CHARLES",
    "LATITUDE": 29.99255,
    "LONGITUDE": -90.39446,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING NEW ORLEANS LLC",
    "CAPACITY": 215000,
    "US_RANK": 33,
    "CRUDE": 215000,
    "IMAGE": "https://drive.google.com/uc?id=114tn7-HFuOq7_EXkmKX6EzrPdGM8EcZA"
  },
  {
    "OBJECTID": 95,
    "NAME": "RICHMOND",
    "ADDRESS": "841 CHEVRON WAY",
    "CITY": "RICHMOND",
    "STATE": "CA",
    "TYPE": "LARGE AND HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1200,
    "COUNTY": "CONTRA COSTA",
    "LATITUDE": 37.94158,
    "LONGITUDE": -122.39145,
    "WEBSITE": "https://www.chevron.com/",
    "OWNER": "CHEVRON CORP",
    "OPERNAME": "CHEVRON USA INC",
    "CAPACITY": 245271,
    "US_RANK": 24,
    "CRUDE": 245271,
    "IMAGE": "https://drive.google.com/uc?id=1gB7EotHFVGNI-r_M-H5-SgWklnf2xjJd"
  },
  {
    "OBJECTID": 96,
    "NAME": "DEER PARK",
    "ADDRESS": "5900 STATE HIGHWAY 225 EAST",
    "CITY": "DEER PARK",
    "STATE": "TX",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1519,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.72153,
    "LONGITUDE": -95.12778,
    "WEBSITE": "http://www.shell.us",
    "OWNER": "DEER PARK REFINING LTD PTNRSHP",
    "OPERNAME": "DEER PARK REFINING LTD PARTNERSHIP",
    "CAPACITY": 325700,
    "US_RANK": 12,
    "CRUDE": 325700,
    "IMAGE": "https://drive.google.com/uc?id=1hUV8Pcg3KL_TGZpz_YsqPZrKjny3Kzpr"
  },
  {
    "OBJECTID": 97,
    "NAME": "LOS ANGELES (CARSON PLANT)",
    "ADDRESS": "1801 E SEPULVEDA BLVD",
    "CITY": "CARSON",
    "STATE": "CA",
    "TYPE": "LARGE AND VERY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1021,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.81535,
    "LONGITUDE": -118.24102,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 269200,
    "US_RANK": 18,
    "CRUDE": 269200,
    "IMAGE": "https://drive.google.com/uc?id=1ICE5o2skU7LM3_VaBadgqwBjiuZsrFaH"
  },
  {
    "OBJECTID": 98,
    "NAME": "SHREVEPORT",
    "ADDRESS": "3333 MIDWAY ST",
    "CITY": "SHREVEPORT",
    "STATE": "LA",
    "TYPE": "SPECIALISED PREMIUM BASE AND PROCESS OILS MANUFACTURING REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 240,
    "COUNTY": "CADDO",
    "LATITUDE": 32.46693,
    "LONGITUDE": -93.79254,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET SHREVEPORT LLC",
    "CAPACITY": 57000,
    "US_RANK": 95,
    "CRUDE": 57000,
    "IMAGE": "https://drive.google.com/uc?id=1XijeivoYecnctJVkthQzdyJOy_hDi2N2"
  },
  {
    "OBJECTID": 99,
    "NAME": "CHANNELVIEW",
    "ADDRESS": "8280 SHELDON ROAD",
    "CITY": "CHANNELVIEW",
    "STATE": "TX",
    "TYPE": "ALKYLATION UNIT",
    "STATUS": "IN SERVICE",
    "POPULATION": 558,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.83178,
    "LONGITUDE": -95.11971,
    "WEBSITE": "http://www.lyondellbasell.com",
    "OWNER": "ACCESS INDUSTRIES",
    "OPERNAME": "EQUISTAR CHEMICALS LP",
    "CAPACITY": 0,
    "US_RANK": 141,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1d7wLITKABxa7A-lCOor_a-EFhSFRnsAt"
  },
  {
    "OBJECTID": 100,
    "NAME": "SUPERIOR",
    "ADDRESS": "2407 STINSON AVENUE",
    "CITY": "SUPERIOR",
    "STATE": "WI",
    "TYPE": "SMALL TO MEDIUM LUBRICANTS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 155,
    "COUNTY": "DOUGLAS",
    "LATITUDE": 46.69135,
    "LONGITUDE": -92.07186,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "HUSKY ENERGY INC",
    "OPERNAME": "CALUMET LUBRICANTS CO LP",
    "CAPACITY": 38000,
    "US_RANK": 105,
    "CRUDE": 38000,
    "IMAGE": "https://drive.google.com/uc?id=1hdBN7eHzwBPCeAu1gNIN03jbNoKxytyq"
  },
  {
    "OBJECTID": 101,
    "NAME": "COMMERCE CITY WEST",
    "ADDRESS": "5801 BRIGHTON BLVD",
    "CITY": "COMMERCE CITY",
    "STATE": "CO",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 125,
    "COUNTY": "ADAMS",
    "LATITUDE": 39.80365,
    "LONGITUDE": -104.94767,
    "WEBSITE": "http://www.suncor.com",
    "OWNER": "SUNCOR ENERGY INC",
    "OPERNAME": "SUNCOR ENERGY (USA) INC",
    "CAPACITY": 67000,
    "US_RANK": 89,
    "CRUDE": 67000,
    "IMAGE": "https://drive.google.com/uc?id=1o92HwpH3SUDnXNskwO8hPJarSNPgeJOT"
  },
  {
    "OBJECTID": 102,
    "NAME": "ROBINSON",
    "ADDRESS": "400 S MARATHON AVE",
    "CITY": "ROBINSON",
    "STATE": "IL",
    "TYPE": "LARGE VERY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 690,
    "COUNTY": "CRAWFORD",
    "LATITUDE": 38.99813,
    "LONGITUDE": -87.71792,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 231000,
    "US_RANK": 27,
    "CRUDE": 231000,
    "IMAGE": "https://drive.google.com/uc?id=1kY5P3FePFILQnlGwjiX1-vgcVYhl5Ozt"
  },
  {
    "OBJECTID": 103,
    "NAME": "MCPHERSON",
    "ADDRESS": "2000 S. MAIN ST",
    "CITY": "MCPHERSON",
    "STATE": "KS",
    "TYPE": "SMALL COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 465,
    "COUNTY": "MCPHERSON",
    "LATITUDE": 38.34404,
    "LONGITUDE": -97.67337,
    "WEBSITE": "http://www.ncra.coop",
    "OWNER": "CHS INC",
    "OPERNAME": "CHS MCPHERSON REFINERY INC",
    "CAPACITY": 96000,
    "US_RANK": 66,
    "CRUDE": 96000,
    "IMAGE": "https://drive.google.com/uc?id=16wtb_zESOSjqVkV6qu14CACUXIigEAds"
  },
  {
    "OBJECTID": 104,
    "NAME": "MARTINEZ",
    "ADDRESS": "150 SOLANO WAY",
    "CITY": "MARTINEZ",
    "STATE": "CA",
    "TYPE": "VERY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 740,
    "COUNTY": "CONTRA COSTA",
    "LATITUDE": 38.0251,
    "LONGITUDE": -122.0639,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 166000,
    "US_RANK": 43,
    "CRUDE": 166000,
    "IMAGE": "https://drive.google.com/uc?id=1DqkCMoI01nGvy4lBAmg7Gj2aKVd-5lRH"
  },
  {
    "OBJECTID": 105,
    "NAME": "BIG SPRING",
    "ADDRESS": "INTERSECTION OF IH 20 AND REFINERY ROAD",
    "CITY": "BIG SPRING",
    "STATE": "TX",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 191,
    "COUNTY": "HOWARD",
    "LATITUDE": 32.27045,
    "LONGITUDE": -101.41632,
    "WEBSITE": "http://www.alonusa.com",
    "OWNER": "ALON ISRAEL OIL COMPANY LTD",
    "OPERNAME": "ALON USA ENERGY INC",
    "CAPACITY": 73000,
    "US_RANK": 84,
    "CRUDE": 73000,
    "IMAGE": "https://drive.google.com/uc?id=1zPitkte0sW8-AwQEbGKSnbgCGsUcvP2n"
  },
  {
    "OBJECTID": 106,
    "NAME": "EL DORADO",
    "ADDRESS": "1401 S DOUGLAS ROAD",
    "CITY": "EL DORADO",
    "STATE": "KS",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 442,
    "COUNTY": "BUTLER",
    "LATITUDE": 37.79594,
    "LONGITUDE": -96.87283,
    "WEBSITE": "http://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER EL DORADO REFINING LLC",
    "CAPACITY": 150000,
    "US_RANK": 50,
    "CRUDE": 150000,
    "IMAGE": "https://drive.google.com/uc?id=12mPKwi419eJNla93Ok_8_eIytPGQWApN"
  },
  {
    "OBJECTID": 107,
    "NAME": "MANDAN",
    "ADDRESS": "900 OLD RED TRAIL NE",
    "CITY": "MANDAN",
    "STATE": "ND",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY THAT PROCESSES LIGHT SWEET CRUDE OIL",
    "STATUS": "IN SERVICE",
    "POPULATION": 290,
    "COUNTY": "MORTON",
    "LATITUDE": 46.85078,
    "LONGITUDE": -100.88122,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 74000,
    "US_RANK": 83,
    "CRUDE": 73800,
    "IMAGE": "https://drive.google.com/uc?id=1iJtV4oxZ8Pl0Pfyo2RvQp0-OkweyzECY"
  },
  {
    "OBJECTID": 108,
    "NAME": "BAKERSFIELD",
    "ADDRESS": "6451 ROSEDALE HIGHWAY",
    "CITY": "BAKERSFIELD",
    "STATE": "CA",
    "TYPE": "MEDIUM SIZED FUELS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 94,
    "COUNTY": "KERN",
    "LATITUDE": 35.3795,
    "LONGITUDE": -119.07206,
    "WEBSITE": "http://bakersfieldrefinery.com",
    "OWNER": "ALON ISRAEL OIL COMPANY LTD",
    "OPERNAME": "ALON BAKERSFIELD OPERATING INC",
    "CAPACITY": 0,
    "US_RANK": 138,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1ZUSKjO540xH9V0W70fGXkVPXED0UMMM9"
  },
  {
    "OBJECTID": 109,
    "NAME": "CATLETTSBURG",
    "ADDRESS": "11631 US RTE 23",
    "CITY": "CATLETTSBURG",
    "STATE": "KY",
    "TYPE": "LARGE MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 740,
    "COUNTY": "BOYD",
    "LATITUDE": 38.37587,
    "LONGITUDE": -82.59843,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 273000,
    "US_RANK": 17,
    "CRUDE": 273000,
    "IMAGE": "https://drive.google.com/uc?id=1AUhUHHBcHgSKeEucqy8AFCgFzGXATRlF"
  },
  {
    "OBJECTID": 110,
    "NAME": "WOOD RIVER",
    "ADDRESS": "900 S CENTRAL AVENUE",
    "CITY": "ROXANA",
    "STATE": "IL",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 840,
    "COUNTY": "MADISON",
    "LATITUDE": 38.83827,
    "LONGITUDE": -90.07398,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "WRB REFINING LP (PHILLIPS66/CENOVUS)",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 336000,
    "US_RANK": 10,
    "CRUDE": 314000,
    "IMAGE": "https://drive.google.com/uc?id=1LJ7T9TcuNIhd-b-u2_7SuL0zKwxeU5_x"
  },
  {
    "OBJECTID": 111,
    "NAME": "WHITING",
    "ADDRESS": "2815 INDIANAPOLIS BLVD",
    "CITY": "WHITING",
    "STATE": "IN",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1849,
    "COUNTY": "LAKE",
    "LATITUDE": 41.66251,
    "LONGITUDE": -87.48195,
    "WEBSITE": "https://www.bp.com",
    "OWNER": "BP PLC",
    "OPERNAME": "BP PRODUCTS NORTH AMERICA INC",
    "CAPACITY": 413500,
    "US_RANK": 7,
    "CRUDE": 413500,
    "IMAGE": "https://drive.google.com/uc?id=1NMqZm1CjtSW_COkZCbCpZKwXD8AQvrUt"
  },
  {
    "OBJECTID": 112,
    "NAME": "DETROIT",
    "ADDRESS": "1300 SOUTH FORT STREET",
    "CITY": "DETROIT",
    "STATE": "MI",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 535,
    "COUNTY": "WAYNE",
    "LATITUDE": 42.28189,
    "LONGITUDE": -83.15623,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 132000,
    "US_RANK": 55,
    "CRUDE": 132000,
    "IMAGE": "https://drive.google.com/uc?id=1_KuuMYfMXPmEdqQaeWke1T_kya5dC527"
  },
  {
    "OBJECTID": 113,
    "NAME": "MEMPHIS",
    "ADDRESS": "543 WEST MALLORY AVE",
    "CITY": "MEMPHIS",
    "STATE": "TN",
    "TYPE": "LARGE MEDIUM COMPLEXITY REFINERY THAT PROCESSES LIGHT SWEET CRUDE",
    "STATUS": "IN SERVICE",
    "POPULATION": 306,
    "COUNTY": "SHELBY",
    "LATITUDE": 35.08508,
    "LONGITUDE": -90.08235,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "PREMCOR REFINING GROUP INC",
    "CAPACITY": 190000,
    "US_RANK": 39,
    "CRUDE": 190000,
    "IMAGE": "https://drive.google.com/uc?id=18GM_QvaGTG20s9R6xFB924FIuwRXTsJm"
  },
  {
    "OBJECTID": 114,
    "NAME": "CONVENT",
    "ADDRESS": "0.7 MILES NORTHEAST OF INTERSECTION OF HWY 70 AND HWY 44",
    "CITY": "CONVENT",
    "STATE": "LA",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 590,
    "COUNTY": "ST. JAMES",
    "LATITUDE": 30.11148,
    "LONGITUDE": -90.89591,
    "WEBSITE": "https://www.shell.us",
    "OWNER": "ROYAL DUTCH SHELL",
    "OPERNAME": "SHELL OIL PRODUCTS US (REFINING)",
    "CAPACITY": 227586,
    "US_RANK": 28,
    "CRUDE": 227586,
    "IMAGE": "https://drive.google.com/uc?id=1PlwsWuw_o6uL6j7vCbxIGQvg963VWKLA"
  },
  {
    "OBJECTID": 115,
    "NAME": "COFFEYVILLE",
    "ADDRESS": "400 N LINDEN STREET",
    "CITY": "COFFEYVILLE",
    "STATE": "KS",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 369,
    "COUNTY": "MONTGOMERY",
    "LATITUDE": 37.05082919,
    "LONGITUDE": -95.60567846,
    "WEBSITE": "http://www.cvrrefining.com",
    "OWNER": "CVR ENERGY",
    "OPERNAME": "COFFEYVILLE RESOURCES RFG & MKTG",
    "CAPACITY": 115000,
    "US_RANK": 60,
    "CRUDE": 115000,
    "IMAGE": "https://drive.google.com/uc?id=1fwpi6B_ZZHkeBRR_MxYQw7CjHwH3noJv"
  },
  {
    "OBJECTID": 116,
    "NAME": "TRAINER",
    "ADDRESS": "4101 POST ROAD",
    "CITY": "TRAINER",
    "STATE": "PA",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY PRODUCES HIGH QUALITY TRANSPORTATION FUELS",
    "STATUS": "IN SERVICE",
    "POPULATION": 304,
    "COUNTY": "DELAWARE",
    "LATITUDE": 39.82213,
    "LONGITUDE": -75.40365,
    "WEBSITE": "http://www.monroe-energy.com",
    "OWNER": "DELTA AIR LINES INC",
    "OPERNAME": "MONROE ENERGY LLC",
    "CAPACITY": 190000,
    "US_RANK": 38,
    "CRUDE": 190000,
    "IMAGE": "https://drive.google.com/uc?id=1vS4PQo3uSMllItGHuSkH0dSCrw_rV3yT"
  },
  {
    "OBJECTID": 117,
    "NAME": "EVANSVILLE",
    "ADDRESS": "5700 EAST HIGHWAY 20-26",
    "CITY": "EVANSVILLE",
    "STATE": "WY",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 112,
    "COUNTY": "NATRONA",
    "LATITUDE": 42.8611,
    "LONGITUDE": -106.24224,
    "WEBSITE": "https://www.sinclairoil.com",
    "OWNER": "SINCLAIR OIL CORP",
    "OPERNAME": "LITTLE AMERICA REFINING CO",
    "CAPACITY": 24500,
    "US_RANK": 115,
    "CRUDE": 24500,
    "IMAGE": "https://drive.google.com/uc?id=1ptK2sfy_rT4b2vV9G_f_JXYClQmFBrpM"
  },
  {
    "OBJECTID": 118,
    "NAME": "WILMINGTON",
    "ADDRESS": "2402 EAST ANAHEIM",
    "CITY": "WILMINGTON",
    "STATE": "CA",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 425,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.77884,
    "LONGITUDE": -118.23507,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO CALIFORNIA",
    "CAPACITY": 85000,
    "US_RANK": 74,
    "CRUDE": 85000,
    "IMAGE": "https://drive.google.com/uc?id=1bhK5Lob_BWJzBZwD5Xj8mhF-4k7RMJQX"
  },
  {
    "OBJECTID": 119,
    "NAME": "GALVESTON BAY",
    "ADDRESS": "2800 FM 519 EAST",
    "CITY": "TEXAS CITY",
    "STATE": "TX",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1790,
    "COUNTY": "GALVESTON",
    "LATITUDE": 29.37217,
    "LONGITUDE": -94.92688,
    "WEBSITE": "https://www.marathonpetroleum.com/",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 459000,
    "US_RANK": 5,
    "CRUDE": 459000,
    "IMAGE": "https://drive.google.com/uc?id=1kcVn17gnGmR6D4qPdZff16XCIL64nPeu"
  },
  {
    "OBJECTID": 120,
    "NAME": "LAUREL",
    "ADDRESS": "803 HWY 212 SOUTH",
    "CITY": "LAUREL",
    "STATE": "MT",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 267,
    "COUNTY": "YELLOWSTONE",
    "LATITUDE": 45.65832,
    "LONGITUDE": -108.76851,
    "WEBSITE": "http://www.chsinc.com",
    "OWNER": "CHS INC",
    "OPERNAME": "CENEX HARVEST STATES COOP",
    "CAPACITY": 59600,
    "US_RANK": 94,
    "CRUDE": 59600,
    "IMAGE": "https://drive.google.com/uc?id=13PSrRjVG44EqCr_kgBiBBuYbwp1AdJFw"
  },
  {
    "OBJECTID": 121,
    "NAME": "CHERRY POINT (FERNDALE)",
    "ADDRESS": "4519 GRANDVIEW ROAD",
    "CITY": "BLAINE",
    "STATE": "WA",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 820,
    "COUNTY": "WHATCOM",
    "LATITUDE": 48.88423,
    "LONGITUDE": -122.73373,
    "WEBSITE": "http://www.bp.com",
    "OWNER": "BP PLC",
    "OPERNAME": "BP WEST COAST PRODUCTS LLC",
    "CAPACITY": 227000,
    "US_RANK": 29,
    "CRUDE": 227000,
    "IMAGE": "https://drive.google.com/uc?id=1TQHk-omlApG_AkstxdP5KPNcP_jkCapz"
  },
  {
    "OBJECTID": 122,
    "NAME": "BILLINGS",
    "ADDRESS": "700 EXXONMOBIL ROAD",
    "CITY": "BILLINGS",
    "STATE": "MT",
    "TYPE": "SMALL COMPLEX REFINERY CAPABLE OF PROCESSING HEAVY & SOUR CRUDE",
    "STATUS": "IN SERVICE",
    "POPULATION": 260,
    "COUNTY": "YELLOWSTONE",
    "LATITUDE": 45.81427,
    "LONGITUDE": -108.43355,
    "WEBSITE": "http://corporate.exxonmobil.com",
    "OWNER": "EXXON MOBIL CORP",
    "OPERNAME": "EXXONMOBIL REFINING & SUPPLY CO",
    "CAPACITY": 61500,
    "US_RANK": 92,
    "CRUDE": 61500,
    "IMAGE": "https://drive.google.com/uc?id=1aS937QoJqD77PF26PyXktSC3exxI5oCm"
  },
  {
    "OBJECTID": 123,
    "NAME": "BILL GREEHEY (CORPUS CHRISTI WEST AND EAST PLANTS)",
    "ADDRESS": "1300 CANTWELL BLVD",
    "CITY": "CORPUS CHRISTI",
    "STATE": "TX",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 800,
    "COUNTY": "NUECES",
    "LATITUDE": 27.8112,
    "LONGITUDE": -97.44167,
    "WEBSITE": "https://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO TEXAS LP",
    "CAPACITY": 293000,
    "US_RANK": 15,
    "CRUDE": 293000,
    "IMAGE": "https://drive.google.com/uc?id=1mGvmEqENky1UBQrgmQQEd9y2XfeD03WT"
  },
  {
    "OBJECTID": 124,
    "NAME": "NORTH POLE",
    "ADDRESS": "1200 H AND H LN",
    "CITY": "NORTH POLE",
    "STATE": "AK",
    "TYPE": "SMALL TOPPING REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "FAIRBANKS NORTH STAR",
    "LATITUDE": 64.73242,
    "LONGITUDE": -147.34401,
    "WEBSITE": "http://www.petrostar.com",
    "OWNER": "ARCTIC SLOPE REGIONAL CORP",
    "OPERNAME": "PETRO STAR INC",
    "CAPACITY": 19700,
    "US_RANK": 119,
    "CRUDE": 19700,
    "IMAGE": "https://drive.google.com/uc?id=1WT9W2d0ChX_XOpS8tX0s8cutVvp2O3qJ"
  },
  {
    "OBJECTID": 125,
    "NAME": "NIXON",
    "ADDRESS": "11372 US HWY 87 E",
    "CITY": "NIXON",
    "STATE": "TX",
    "TYPE": "VERY SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "WILSON",
    "LATITUDE": 29.26145,
    "LONGITUDE": -97.78658,
    "WEBSITE": "http://www.blue-dolphin-energy.com",
    "OWNER": "BLUE DOLPHIN ENERGY CO",
    "OPERNAME": "LAZARUS ENERGY LLC",
    "CAPACITY": 13765,
    "US_RANK": 124,
    "CRUDE": 13765,
    "IMAGE": "https://drive.google.com/uc?id=15SPzpRWuRfQ1DyHwfXq9tHesIJQBO8gO"
  },
  {
    "OBJECTID": 126,
    "NAME": "PRUDHOE BAY",
    "ADDRESS": "NOT AVAILABLE",
    "CITY": "PRUDHOE BAY",
    "STATE": "AK",
    "TYPE": "OIL FIELD TOPPING UNIT",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "NORTH SLOPE (B)",
    "LATITUDE": 70.25498,
    "LONGITUDE": -148.34731,
    "WEBSITE": "https://www.bp.com",
    "OWNER": "BP PLC",
    "OPERNAME": "BP EXPLORATION ALASKA INC",
    "CAPACITY": 6500,
    "US_RANK": 132,
    "CRUDE": 6500,
    "IMAGE": "https://drive.google.com/uc?id=1GbYv520fwQORZmJ8fh6TpQUXJ2YjFx8Z"
  },
  {
    "OBJECTID": 127,
    "NAME": "PRINCETON",
    "ADDRESS": "10234 HWY 157",
    "CITY": "PRINCETON",
    "STATE": "LA",
    "TYPE": "SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "BOSSIER",
    "LATITUDE": 32.59091,
    "LONGITUDE": -93.51259,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET LUBRICANTS CO LP",
    "CAPACITY": 8300,
    "US_RANK": 130,
    "CRUDE": 8300,
    "IMAGE": "https://drive.google.com/uc?id=1gWam2Tonz-Isli8n13nyA-Sl4z64yvwE"
  },
  {
    "OBJECTID": 128,
    "NAME": "PRUDHOE BAY",
    "ADDRESS": "NOT AVAILABLE",
    "CITY": "KUPARUK",
    "STATE": "AK",
    "TYPE": "OIL FIELD TOPPING UNIT",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "NORTH SLOPE (B)",
    "LATITUDE": 70.32539,
    "LONGITUDE": -149.6059,
    "WEBSITE": "http://www.conocophillips.com",
    "OWNER": "CONOCOPHILLIPS",
    "OPERNAME": "CONOCOPHILLIPS ALASKA INC",
    "CAPACITY": 15000,
    "US_RANK": 123,
    "CRUDE": 15000,
    "IMAGE": "https://drive.google.com/uc?id=1bb69DBoInz9oLa3fTj28NjwW-A1MVv2k"
  },
  {
    "OBJECTID": 129,
    "NAME": "ELY",
    "ADDRESS": "HC 34 BOX 34830 AND 65 MILES SW OF ELY ON HWY 6",
    "CITY": "ELY",
    "STATE": "NV",
    "TYPE": "VERY SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "NYE",
    "LATITUDE": 38.6222,
    "LONGITUDE": -115.61858,
    "WEBSITE": "NOT AVAILABLE",
    "OWNER": "FORELAND REFINING CORP",
    "OPERNAME": "FORELAND REFINING CORP",
    "CAPACITY": 2000,
    "US_RANK": 137,
    "CRUDE": 2000,
    "IMAGE": "https://drive.google.com/uc?id=1pHSnDTNwy9mFHsINntrbqIt9VQHBy9sW"
  },
  {
    "OBJECTID": 130,
    "NAME": "ATMORE",
    "ADDRESS": "4745 ROSS ROAD",
    "CITY": "ATMORE",
    "STATE": "AL",
    "TYPE": "VERY SMALL TOPPING REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "ESCAMBIA",
    "LATITUDE": 31.18137,
    "LONGITUDE": -87.4394,
    "WEBSITE": "http://www.goodwayrefining.com",
    "OWNER": "GOODWAY REFINING LLC",
    "OPERNAME": "GOODWAY REFINING LLC",
    "CAPACITY": 4100,
    "US_RANK": 135,
    "CRUDE": 4100,
    "IMAGE": "https://drive.google.com/uc?id=1slCp0tJ74Wl7H5GrZ21kbrh2aSypoZBz"
  },
  {
    "OBJECTID": 131,
    "NAME": "SANTA MARIA ASPHALT REFINERY",
    "ADDRESS": "1700 SINTON ROAD",
    "CITY": "SANTA MARIA",
    "STATE": "CA",
    "TYPE": "LARGE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 126,
    "COUNTY": "SANTA BARBARA",
    "LATITUDE": 34.93032,
    "LONGITUDE": -120.51069,
    "WEBSITE": "http://www.greka.com",
    "OWNER": "GREKA ENERGY",
    "OPERNAME": "SANTA MARIA REFINING COMPANY",
    "CAPACITY": 9500,
    "US_RANK": 128,
    "CRUDE": 9500,
    "IMAGE": "https://drive.google.com/uc?id=1oumtt34nFYJj1OCePm-yjMj7aUWVZ3nR"
  },
  {
    "OBJECTID": 132,
    "NAME": "PAULSBORO",
    "ADDRESS": "4 PARADISE ROAD",
    "CITY": "PAULSBORO",
    "STATE": "NJ",
    "TYPE": "SPECIALIST ASPHALT REFINERY",
    "STATUS": "CLOSED",
    "POPULATION": 80,
    "COUNTY": "GLOUCESTER",
    "LATITUDE": 39.84615,
    "LONGITUDE": -75.2256,
    "WEBSITE": "http://axeonsp.com/",
    "OWNER": "LINDSAY GOLDBERG LLC",
    "OPERNAME": "AXEON SPECIALTY PRODUCTS LLC",
    "CAPACITY": 74000,
    "US_RANK": 82,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1eob64z0zBWhQwhdK5TDvlXqmMfqsTMtH"
  },
  {
    "OBJECTID": 133,
    "NAME": "BAKERSFIELD",
    "ADDRESS": "3542 SHELL ST",
    "CITY": "BAKERSFIELD",
    "STATE": "CA",
    "TYPE": "SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "KERN",
    "LATITUDE": 35.39724,
    "LONGITUDE": -119.04671,
    "WEBSITE": "http://www.sjr.com",
    "OWNER": "SAN JOAQUIN REFINING CO INC",
    "OPERNAME": "SAN JOAQUIN REFINING CO INC",
    "CAPACITY": 15000,
    "US_RANK": 121,
    "CRUDE": 15000,
    "IMAGE": "https://drive.google.com/uc?id=1H1f40pVO95EeOrE4mKwimU4Z9ZQldzsI"
  },
  {
    "OBJECTID": 134,
    "NAME": "WILMINGTON ASPHALT PLANT",
    "ADDRESS": "1651 S ALAMEDA STREET",
    "CITY": "WILMINGTON",
    "STATE": "CA",
    "TYPE": "SMALL ASPHALT REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.7976,
    "LONGITUDE": -118.23925,
    "WEBSITE": "https://www.valero.com/en-us",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO CALIFORNIA",
    "CAPACITY": 6300,
    "US_RANK": 133,
    "CRUDE": 6300,
    "IMAGE": "https://drive.google.com/uc?id=17ZTJKOUEei0FVWcuX8sqqQJqR5ADYzie"
  },
  {
    "OBJECTID": 135,
    "NAME": "BURNABY",
    "ADDRESS": "5201 PENZANCE DRIVE AND 355 N WILLINGDON AVENUE",
    "CITY": "BURNABY",
    "STATE": "BC",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 250,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 49.29336,
    "LONGITUDE": -122.98734,
    "WEBSITE": "http://www.parkland.ca/en/",
    "OWNER": "PARKLAND FUEL CORPORATION",
    "OPERNAME": "PARKLAND FUEL CORPORATION",
    "CAPACITY": 55000,
    "US_RANK": -999,
    "CRUDE": 54721,
    "IMAGE": "https://drive.google.com/uc?id=1HvP-7MwknM1VZqIyHlhHKUeQ0F-jeZDh"
  },
  {
    "OBJECTID": 136,
    "NAME": "REGINA (CO-OP REFINERY COMPLEX)",
    "ADDRESS": "9 AVENUE N AND MCDONALD STREET",
    "CITY": "REGINA",
    "STATE": "SK",
    "TYPE": "SMALL TOPPING REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 800,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 50.48602,
    "LONGITUDE": -104.57294,
    "WEBSITE": "http://www.ccrl-fcl.ca",
    "OWNER": "FEDERATED CO-OPERATIVES LIMITED (FCL)",
    "OPERNAME": "FCL CO-OP REFINERY COMPLEX",
    "CAPACITY": 135000,
    "US_RANK": -999,
    "CRUDE": 135231,
    "IMAGE": "https://drive.google.com/uc?id=1LKsF1-3Uf_ZdmS2Px1nZ9A3ZjiFdltf5"
  },
  {
    "OBJECTID": 137,
    "NAME": "JEAN GAULIN",
    "ADDRESS": "165 CHEMIN DES ILES",
    "CITY": "LEVIS",
    "STATE": "QC",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 500,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 46.75882,
    "LONGITUDE": -71.19313,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORPORATION",
    "OPERNAME": "VALERO ENERGY INC",
    "CAPACITY": 265000,
    "US_RANK": -999,
    "CRUDE": 264990,
    "IMAGE": "https://drive.google.com/uc?id=13syXVCn29zpPsgJe8K5cCDAOuNkNV54D"
  },
  {
    "OBJECTID": 138,
    "NAME": "SARNIA",
    "ADDRESS": "602 CHRISTINA STREET SOUTH",
    "CITY": "SARNIA",
    "STATE": "ON",
    "TYPE": "MEDIUM TO LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 392,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 42.95168,
    "LONGITUDE": -82.41765,
    "WEBSITE": "http://www.imperialoil.ca",
    "OWNER": "IMPERIAL OIL",
    "OPERNAME": "IMPERIAL OIL LTD",
    "CAPACITY": 121000,
    "US_RANK": -999,
    "CRUDE": 118997,
    "IMAGE": "https://drive.google.com/uc?id=1Ythiv_ZWqGK3d04qj8jj961kvIDgBtys"
  },
  {
    "OBJECTID": 139,
    "NAME": "SAINT JOHN",
    "ADDRESS": "340 LOCH LOMOND ROAD",
    "CITY": "SAINT JOHN",
    "STATE": "NB",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1400,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 45.28335,
    "LONGITUDE": -66.0092,
    "WEBSITE": "https://www.irvingoilcommercial.com",
    "OWNER": "IRVING OIL",
    "OPERNAME": "IRVING OIL",
    "CAPACITY": 300000,
    "US_RANK": -999,
    "CRUDE": 298766,
    "IMAGE": "https://drive.google.com/uc?id=127AvN4jXpjqwahR8BXIe2RsC1tQRf_Jb"
  },
  {
    "OBJECTID": 140,
    "NAME": "NANTICOKE",
    "ADDRESS": "225 CONCESSION 2 WALPOLE ROAD",
    "CITY": "NANTICOKE",
    "STATE": "ON",
    "TYPE": "MEDIUM TO LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 287,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 42.83385,
    "LONGITUDE": -80.0478,
    "WEBSITE": "http://www.imperialoil.ca",
    "OWNER": "IMPERIAL OIL",
    "OPERNAME": "IMPERIAL OIL LTD",
    "CAPACITY": 112000,
    "US_RANK": -999,
    "CRUDE": 113500,
    "IMAGE": "https://drive.google.com/uc?id=1dGFKtSp_DHM1t8fmjcW7q-yLjx92KhDn"
  },
  {
    "OBJECTID": 141,
    "NAME": "SMACKOVER",
    "ADDRESS": "484 E 6TH STREET",
    "CITY": "SMACKOVER",
    "STATE": "AR",
    "TYPE": "VERY SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "UNION",
    "LATITUDE": 33.36335,
    "LONGITUDE": -92.71255,
    "WEBSITE": "http://www.themartincompanies.com",
    "OWNER": "MARTIN RESOURCE MANAGEMENT GRP",
    "OPERNAME": "CROSS OIL REFINING & MARKETING INC",
    "CAPACITY": 7500,
    "US_RANK": 131,
    "CRUDE": 7500,
    "IMAGE": "https://drive.google.com/uc?id=11UYNblv3p2VCkDxZh0qY4bEcc8gXSMPm"
  },
  {
    "OBJECTID": 142,
    "NAME": "CADEREYTA (ING. HECTOR R LARA SOSA)",
    "ADDRESS": "KM 36 AUTOPISTA REYNOSA-MONTERREY",
    "CITY": "CADEREYTA JIMENEZ",
    "STATE": "NL",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 500,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 25.5877,
    "LONGITUDE": -99.94061,
    "WEBSITE": "http://www.ref.pemex.com",
    "OWNER": "PEMEX",
    "OPERNAME": "PETROLEOS MEXICANOS (PEMEX)",
    "CAPACITY": 275000,
    "US_RANK": -999,
    "CRUDE": 275000,
    "IMAGE": "https://drive.google.com/uc?id=1t3oZfB6jk7Px4ar-Pkvf6jIk6c9Af3jc"
  },
  {
    "OBJECTID": 143,
    "NAME": "CORUNNA (SARNIA MANUFACTURING CENTRE (SMC))",
    "ADDRESS": "150 ST. CLAIR PARKWAY",
    "CITY": "CORUNNA",
    "STATE": "ON",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 350,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 42.90668,
    "LONGITUDE": -82.44486,
    "WEBSITE": "http://www.shell.ca",
    "OWNER": "SHELL",
    "OPERNAME": "SHELL OIL PRODUCTS CANADA",
    "CAPACITY": 75000,
    "US_RANK": -999,
    "CRUDE": 77000,
    "IMAGE": "https://drive.google.com/uc?id=1_skNiFgjuNqogkk0WSmxZ3pFq8-5EBgu"
  },
  {
    "OBJECTID": 144,
    "NAME": "PETRO-CANADA LUBRICANTS (CLARKSON)",
    "ADDRESS": "2310 LAKESHORE ROAD WEST",
    "CITY": "MISSISSAUGA",
    "STATE": "ON",
    "TYPE": "LUBRICANTS PLANT/REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 43.50178,
    "LONGITUDE": -79.61003,
    "WEBSITE": "http://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER REFINING LLC",
    "CAPACITY": 15600,
    "US_RANK": -999,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1ZHpTgWRmEImsRWYviaNZOGZ4jC1X4uBY"
  },
  {
    "OBJECTID": 145,
    "NAME": "MONTREAL",
    "ADDRESS": "11701 SHERBROOKE STREET EAST",
    "CITY": "MONTREAL",
    "STATE": "QC",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 400,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 45.64297,
    "LONGITUDE": -73.52408,
    "WEBSITE": "http://www.suncor.com",
    "OWNER": "SUNCOR",
    "OPERNAME": "SUNCOR ENERGY PRODUCTS PARTNERSHIP",
    "CAPACITY": 137000,
    "US_RANK": -999,
    "CRUDE": 136998,
    "IMAGE": "https://drive.google.com/uc?id=1MDB8qil7WXOldN4BjHlZSFmfqnRX6f7G"
  },
  {
    "OBJECTID": 146,
    "NAME": "SARNIA",
    "ADDRESS": "1900 ST. CLAIR PARKWAY",
    "CITY": "SARNIA",
    "STATE": "ON",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "NOT AVAILABLE",
    "LATITUDE": 42.93098,
    "LONGITUDE": -82.43958,
    "WEBSITE": "http://www.suncor.com",
    "OWNER": "SUNCOR",
    "OPERNAME": "SUNCOR ENERGY PRODUCTS PARTNERSHIP",
    "CAPACITY": 85000,
    "US_RANK": -999,
    "CRUDE": 85001,
    "IMAGE": "https://drive.google.com/uc?id=1XFZ3-aFHlr8rawFB1aBo8MYcoL2OuClz"
  },
  {
    "OBJECTID": 147,
    "NAME": "GALENA PARK SPLITTER",
    "ADDRESS": "407 CLINTON DR",
    "CITY": "GALENA PARK",
    "STATE": "TX",
    "TYPE": "CONDENSATE SPLITTER",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.737676,
    "LONGITUDE": -95.218204,
    "WEBSITE": "https://www.kindermorgan.com",
    "OWNER": "KINDER MORGAN ENERGY PTNRS LP",
    "OPERNAME": "KINDER MORGAN CRUDE & CONDENSATE",
    "CAPACITY": 84000,
    "US_RANK": 78,
    "CRUDE": 84000,
    "IMAGE": "https://drive.google.com/uc?id=1eHe3JObnhqP41lQgNmemzc5YoqlVDURU"
  },
  {
    "OBJECTID": 148,
    "NAME": "CORPUS CHRISTI",
    "ADDRESS": "7209 UP RIVER RD",
    "CITY": "CORPUS CHRISTI",
    "STATE": "TX",
    "TYPE": "CONDENSATE SPLITTER",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "NUECES",
    "LATITUDE": 27.81794,
    "LONGITUDE": -97.507191,
    "WEBSITE": "http://www.buckeye.com/",
    "OWNER": "BUCKEYE PARTNERS LP",
    "OPERNAME": "BUCKEYE TEXAS PROCESSING LLC",
    "CAPACITY": 46250,
    "US_RANK": 100,
    "CRUDE": 46250,
    "IMAGE": "https://drive.google.com/uc?id=1KXyWrhK-q6Ky6rjAbsgjwvs1jB1ZUC8d"
  },
  {
    "OBJECTID": 149,
    "NAME": "CORPUS CHRISTI CONDENSATE SPLITTER",
    "ADDRESS": "1802 POTH LN/15 COUNTRY CLUB DRIVE",
    "CITY": "CORPUS CHRISTI",
    "STATE": "TX",
    "TYPE": "CONDENSATE SPLITTER",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "NUECES",
    "LATITUDE": 27.809312,
    "LONGITUDE": -97.436169,
    "WEBSITE": "https://www.magellanlp.com/",
    "OWNER": "MAGELLAN MIDSTREAM PARTNERS LP",
    "OPERNAME": "MAGELLAN TERMINAL HOLDINGS LP",
    "CAPACITY": 42500,
    "US_RANK": 102,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1XQgjNKazzGcUxEnzVduEAPNgQLlOdyeF"
  },
  {
    "OBJECTID": 150,
    "NAME": "HOUSTON",
    "ADDRESS": "1519 SOUTH SHELDON RD",
    "CITY": "HOUSTON",
    "STATE": "TX",
    "TYPE": "CRUDE OIL FRACTIONATION",
    "STATUS": "IN SERVICE",
    "POPULATION": -999,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.751112,
    "LONGITUDE": -95.122762,
    "WEBSITE": "http://www.petromaxrefining.com",
    "OWNER": "PETROMAX REFINING CO LLC",
    "OPERNAME": "PETROMAX REFINING CO LLC",
    "CAPACITY": 25000,
    "US_RANK": 114,
    "CRUDE": 25000,
    "IMAGE": "https://drive.google.com/uc?id=18YkXN0YNM1ntpQm5a-ddQWhBfLUPyfoK"
  },
  {
    "OBJECTID": 151,
    "NAME": "DICKINSON",
    "ADDRESS": "3815 116TH AVE SW",
    "CITY": "DICKINSON",
    "STATE": "ND",
    "TYPE": "SMALL HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 90,
    "COUNTY": "STARK",
    "LATITUDE": 46.855298,
    "LONGITUDE": -102.912698,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 20000,
    "US_RANK": 118,
    "CRUDE": 19500,
    "IMAGE": "https://drive.google.com/uc?id=14pNtBJ41AXlEWEgB_CgS2XSV60UDvKWl"
  },
  {
    "OBJECTID": 152,
    "NAME": "PELICAN - LAKE CHARLES",
    "ADDRESS": "4646 LA HWY 3059 (OLD TOWN ROAD)",
    "CITY": "LAKE CHARLES",
    "STATE": "LA",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "CLOSED",
    "POPULATION": 45,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.28776,
    "LONGITUDE": -93.14512,
    "WEBSITE": "http://pelican-refinery.com/",
    "OWNER": "PELICAN REFINING COMPANY LLC",
    "OPERNAME": "PELICAN REFINING COMPANY LLC",
    "CAPACITY": 0,
    "US_RANK": -999,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1agEIpdalkFQ5hD3jlG9ME3l_iEpQAWmZ"
  },
  {
    "OBJECTID": 153,
    "NAME": "TRIGEANT PETROLEUM - CORPUS CHRISTI",
    "ADDRESS": "6600 UP RIVER ROAD",
    "CITY": "CORPUS CHRISTI",
    "STATE": "TX",
    "TYPE": "ASPHALT REFINERY",
    "STATUS": "CLOSED",
    "POPULATION": -999,
    "COUNTY": "NUECES",
    "LATITUDE": 27.81738,
    "LONGITUDE": -97.49173,
    "WEBSITE": "http://www.pinoakcorpus.com/",
    "OWNER": "BTB REFINING LLC (GRAVITY)",
    "OPERNAME": "TRIGEANT PETROLEUM LTD",
    "CAPACITY": 0,
    "US_RANK": -999,
    "CRUDE": 0,
    "IMAGE": "https://drive.google.com/uc?id=1kqIHAipr3yKKJJ8xqU-Qz_skby3zx4TW"
  },
  {
    "OBJECTID": 154,
    "NAME": "ANTELOPE REFINING - DOUGLAS",
    "ADDRESS": "2070 STATE HIGHWAY 59",
    "CITY": "DOUGLAS",
    "STATE": "WY",
    "TYPE": "VERY SMALL SIMPLE REFINERY",
    "STATUS": "CLOSED",
    "POPULATION": -999,
    "COUNTY": "CONVERSE",
    "LATITUDE": 43.01965,
    "LONGITUDE": -105.26072,
    "WEBSITE": "http://www.genesisenergy.com/",
    "OWNER": "GENESIS ENERGY LP",
    "OPERNAME": "ANTELOPE REFINING LLC",
    "CAPACITY": 3800,
    "US_RANK": -999,
    "CRUDE": 3800,
    "IMAGE": "https://drive.google.com/uc?id=1CXfC0FUlRPn2WKU-cPIqrQEvFX30plAh"
  },
  {
    "OBJECTID": 155,
    "NAME": "SANTA MARIA",
    "ADDRESS": "2555 WILLOW ROAD",
    "CITY": "ARROYO GRANDE",
    "STATE": "CA",
    "TYPE": "SMALL COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 140,
    "COUNTY": "SAN LUIS OBISPO",
    "LATITUDE": 35.03871984,
    "LONGITUDE": -120.5895394,
    "WEBSITE": "https://www.phillips66.com/",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 41800,
    "US_RANK": -999,
    "CRUDE": 41800,
    "IMAGE": "https://drive.google.com/uc?id=1eeFbulN1nYjqp0XdWaNSsl4RrtY_HG8e"
  }
]