/*const data = [
  {
    "OBJECTID": 1,
    "NAME": "SOMERSET",
    "ADDRESS": "300 REFINERY ROAD",
    "CITY": "SOMERSET",
    "STATE": "KY",
    "TYPE": "VERY SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 34,
    "COUNTY": "PULASKI",
    "LATITUDE": 37.07113,
    "LONGITUDE": -84.60951,
    "WEBSITE": "http://www.continentalrefiningco.com",
    "OWNER": "CONTINENTAL REFINING CO LLC",
    "OPERNAME": "CONTINENTAL REFINING COMPANY LLC",
    "CAPACITY": 5500,
    "US_RANK": 134,
    "CRUDE": 5500,
    "URL": "https://drive.google.com/uc?id=1Qw68r2sgDP4PgdbcS9FTDTnHnfIgnL4H"
  },
  {
    "OBJECTID": 2,
    "NAME": "WOODS CROSS",
    "ADDRESS": "2355 SOUTH 1100 WEST",
    "CITY": "WOODS CROSS",
    "STATE": "UT",
    "TYPE": "VERY SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 45,
    "COUNTY": "DAVIS",
    "LATITUDE": 40.86776,
    "LONGITUDE": -111.91,
    "WEBSITE": "http://silvereagleenergy.com",
    "OWNER": "SILVER EAGLE REFINING INC",
    "OPERNAME": "SILVER EAGLE REFINING",
    "CAPACITY": 15000,
    "US_RANK": 122,
    "CRUDE": 15000,
    "URL": "https://drive.google.com/uc?id=1yY5_zJxsYhVjKg6qqM15stfov4aZIK7T"
  },
  {
    "OBJECTID": 3,
    "NAME": "COMMERCE CITY EAST",
    "ADDRESS": "5801 BRIGHTON BLVD",
    "CITY": "COMMERCE CITY",
    "STATE": "CO",
    "TYPE": "SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 420,
    "COUNTY": "ADAMS",
    "LATITUDE": 39.80175,
    "LONGITUDE": -104.94518,
    "WEBSITE": "http://www.suncor.com",
    "OWNER": "SUNCOR ENERGY INC",
    "OPERNAME": "SUNCOR ENERGY (USA) INC",
    "CAPACITY": 36000,
    "US_RANK": 107,
    "CRUDE": 36000,
    "URL": "https://drive.google.com/uc?id=15nahl_XM_xSBy3piXPn9zSnvs0vzb3wQ"
  },
  {
    "OBJECTID": 4,
    "NAME": "SAN ANTONIO",
    "ADDRESS": "7811 S PRESA STREET",
    "CITY": "SAN ANTONIO",
    "STATE": "TX",
    "TYPE": "SMALL LUBRICANTS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 50,
    "COUNTY": "BEXAR",
    "LATITUDE": 29.34757,
    "LONGITUDE": -98.46019,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET LUBRICANTS CO",
    "CAPACITY": 20000,
    "US_RANK": 117,
    "CRUDE": 20000,
    "URL": "https://drive.google.com/uc?id=1I7mgnNKmSUrhYHkVDysrmp0bqNGWTb-a"
  },
  {
    "OBJECTID": 5,
    "NAME": "PAULSBORO",
    "ADDRESS": "800 BILLINGSPORT ROAD",
    "CITY": "PAULSBORO",
    "STATE": "NJ",
    "TYPE": "LARGE HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 427,
    "COUNTY": "GLOUCESTER",
    "LATITUDE": 39.84038,
    "LONGITUDE": -75.25681,
    "WEBSITE": "http://www.pbfenergy.com",
    "OWNER": "PBF ENERGY CO LLC",
    "OPERNAME": "PAULSBORO REFINING CO LLC",
    "CAPACITY": 160000,
    "US_RANK": 44,
    "CRUDE": 160000,
    "URL": "https://drive.google.com/uc?id=1KTkxzPZgIX1op03gbPkQhRLEJbevXV-F"
  },
  {
    "OBJECTID": 6,
    "NAME": "TEXAS CITY",
    "ADDRESS": "1301 LOOP 197 SOUTH",
    "CITY": "TEXAS CITY",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 509,
    "COUNTY": "GALVESTON",
    "LATITUDE": 29.36763,
    "LONGITUDE": -94.90828,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO TEXAS LP",
    "CAPACITY": 225000,
    "US_RANK": 32,
    "CRUDE": 225000,
    "URL": "https://drive.google.com/uc?id=1iKrPeq4WO6Bu6y7zyIBDgYtyZK-6mDRD"
  },
  {
    "OBJECTID": 7,
    "NAME": "TEXAS CITY",
    "ADDRESS": "502 10TH STREET SOUTH",
    "CITY": "TEXAS CITY",
    "STATE": "TX",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY THAT PROCESSES SWEET CRUDE",
    "STATUS": "IN SERVICE",
    "POPULATION": 276,
    "COUNTY": "GALVESTON",
    "LATITUDE": 29.37542,
    "LONGITUDE": -94.90798,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 86000,
    "US_RANK": 73,
    "CRUDE": 86000,
    "URL": "https://drive.google.com/uc?id=1lVn5Jhpnkzie0DrxqLKs39VnUIpYDmjD"
  },
  {
    "OBJECTID": 8,
    "NAME": "BAYTOWN",
    "ADDRESS": "2800 DECKER DR/4500 BAYWAY DRIVE",
    "CITY": "BAYTOWN",
    "STATE": "TX",
    "TYPE": "VERY LARGE AND HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1307,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.74285,
    "LONGITUDE": -95.01026,
    "WEBSITE": "http://www.exxonmobilchemical.com",
    "OWNER": "EXXON MOBIL CORP",
    "OPERNAME": "EXXONMOBIL REFINING & SUPPLY CO",
    "CAPACITY": 560500,
    "US_RANK": 2,
    "CRUDE": 560500,
    "URL": "https://drive.google.com/uc?id=1Yjtygk9RdoNbD1ObMzpwkIaYtP3plNJO"
  },
  {
    "OBJECTID": 9,
    "NAME": "CHALMETTE",
    "ADDRESS": "500 WEST ST. BERNARD HWY",
    "CITY": "CHALMETTE",
    "STATE": "LA",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 625,
    "COUNTY": "ST. BERNARD",
    "LATITUDE": 29.93358,
    "LONGITUDE": -89.96916,
    "WEBSITE": "http://corporate.exxonmobil.com",
    "OWNER": "PBF ENERGY CO LLC",
    "OPERNAME": "CHALMETTE REFINING LLC",
    "CAPACITY": 190000,
    "US_RANK": 37,
    "CRUDE": 190000,
    "URL": "https://drive.google.com/uc?id=1VcfkEmzOqSXv0GIegCFlBMiN1oNnQSU_"
  },
  {
    "OBJECTID": 10,
    "NAME": "TOLEDO",
    "ADDRESS": "4001 CEDAR POINT ROAD",
    "CITY": "OREGON",
    "STATE": "OH",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 465,
    "COUNTY": "LUCAS",
    "LATITUDE": 41.67947,
    "LONGITUDE": -83.45156,
    "WEBSITE": "http://www.huskyenergy.com",
    "OWNER": "BP HUSKY REFINING LLC",
    "OPERNAME": "BP-HUSKY REFINING LLC",
    "CAPACITY": 153000,
    "US_RANK": 48,
    "CRUDE": 153000,
    "URL": "https://drive.google.com/uc?id=1HRhpVpUTusH9OUTlyh2r4KWADq0am5NH"
  },
  {
    "OBJECTID": 11,
    "NAME": "THREE RIVERS",
    "ADDRESS": "301 LEROY STREET",
    "CITY": "THREE RIVERS",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 302,
    "COUNTY": "LIVE OAK",
    "LATITUDE": 28.45728,
    "LONGITUDE": -98.18771,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO ENERGY CORPORATION",
    "CAPACITY": 89000,
    "US_RANK": 71,
    "CRUDE": 89000,
    "URL": "https://drive.google.com/uc?id=11jWmHYGS4KeVAB-gznu9ihu_T5JF7fuL"
  },
  {
    "OBJECTID": 12,
    "NAME": "HOUSTON",
    "ADDRESS": "9701 MANCHESTER",
    "CITY": "HOUSTON",
    "STATE": "TX",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 340,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.72181,
    "LONGITUDE": -95.2536,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO REFINING CO TEXAS LP",
    "CAPACITY": 191000,
    "US_RANK": 36,
    "CRUDE": 191000,
    "URL": "https://drive.google.com/uc?id=137SDEMpvfi0IHa5ngVagaKCAhVVHCJpl"
  },
  {
    "OBJECTID": 13,
    "NAME": "SINCLAIR",
    "ADDRESS": "100 E LINCOLN AVENUE (EAST LINCOLN HIGHWAY)",
    "CITY": "SINCLAIR",
    "STATE": "WY",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 332,
    "COUNTY": "CARBON",
    "LATITUDE": 41.78212,
    "LONGITUDE": -107.10722,
    "WEBSITE": "http://www.sinclairoil.com",
    "OWNER": "SINCLAIR OIL CORP",
    "OPERNAME": "SINCLAIR WYOMING REFINING CO",
    "CAPACITY": 85000,
    "US_RANK": 76,
    "CRUDE": 85000,
    "URL": "https://drive.google.com/uc?id=1Aan7o45g8XDZhIUFtFCnubGRCnCvFRbQ"
  },
  {
    "OBJECTID": 14,
    "NAME": "TYLER",
    "ADDRESS": "1702 E COMMERCE STREET",
    "CITY": "TYLER",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 254,
    "COUNTY": "SMITH",
    "LATITUDE": 32.36172,
    "LONGITUDE": -95.2797,
    "WEBSITE": "http://www.delekus.com",
    "OWNER": "DELEK GROUP LTD",
    "OPERNAME": "DELEK REFINING LTD",
    "CAPACITY": 72000,
    "US_RANK": 86,
    "CRUDE": 72000,
    "URL": "https://drive.google.com/uc?id=1CQyaQxRKLCMTpwe1xXyj9818QYqwIG_Q"
  },
  {
    "OBJECTID": 15,
    "NAME": "MARTINEZ",
    "ADDRESS": "3485 PACHECO BLVD",
    "CITY": "MARTINEZ",
    "STATE": "CA",
    "TYPE": "LARGE HIGHLY COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 774,
    "COUNTY": "CONTRA COSTA",
    "LATITUDE": 38.01844,
    "LONGITUDE": -122.11327,
    "WEBSITE": "http://www.shell.us",
    "OWNER": "ROYAL DUTCH/SHELL GROUP",
    "OPERNAME": "SHELL OIL PRODUCTS US",
    "CAPACITY": 156400,
    "US_RANK": 47,
    "CRUDE": 156400,
    "URL": "https://drive.google.com/uc?id=1dntt4bVm_mEdZEKSejQfvEFYqTLER9GP"
  },
  {
    "OBJECTID": 16,
    "NAME": "SUNRAY",
    "ADDRESS": "6701 FM 119",
    "CITY": "SUNRAY",
    "STATE": "TX",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 435,
    "COUNTY": "MOORE",
    "LATITUDE": 35.95528,
    "LONGITUDE": -101.88038,
    "WEBSITE": "http://www.valero.com",
    "OWNER": "VALERO ENERGY CORP",
    "OPERNAME": "VALERO ENERGY CORPORATION",
    "CAPACITY": 195000,
    "US_RANK": 35,
    "CRUDE": 195000,
    "URL": "https://drive.google.com/uc?id=14Lwj4JtLva73dqwMdXm3A7eRC-pvRJAX"
  },
  {
    "OBJECTID": 17,
    "NAME": "PASADENA",
    "ADDRESS": "111 RED BLUFF ROAD",
    "CITY": "PASADENA",
    "STATE": "TX",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY WITH A HIGH GASOLINE YIELD",
    "STATUS": "IN SERVICE",
    "POPULATION": 345,
    "COUNTY": "HARRIS",
    "LATITUDE": 29.7231,
    "LONGITUDE": -95.20804,
    "WEBSITE": "http://www.petrobras.com",
    "OWNER": "PETROBRAS AMERICA INC",
    "OPERNAME": "PASADENA REFINING SYSTEMS INC",
    "CAPACITY": 112229,
    "US_RANK": 61,
    "CRUDE": 112229,
    "URL": "https://drive.google.com/uc?id=16ClQsFX3Kt7hDnIHiHVWxq-TSxiB_so6"
  },
  {
    "OBJECTID": 18,
    "NAME": "LAKE CHARLES",
    "ADDRESS": "1601 HWY 108 E",
    "CITY": "SULPHUR",
    "STATE": "LA",
    "TYPE": "MODERN DEEP-CONVERSION FACILITY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1183,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.17866697,
    "LONGITUDE": -93.33023518,
    "WEBSITE": "http://citgorefining.com",
    "OWNER": "PDV AMERICA INC",
    "OPERNAME": "CITGO PETROLEUM CORP",
    "CAPACITY": 425000,
    "US_RANK": 6,
    "CRUDE": 425000,
    "URL": "https://drive.google.com/uc?id=1MzS-8SItDUmAIuuEw7MiQWLmkorZ4M_z"
  },
  {
    "OBJECTID": 19,
    "NAME": "RODEO (SAN FRANCISCO)",
    "ADDRESS": "1380 SAN PABLO AVENUE",
    "CITY": "RODEO",
    "STATE": "CA",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 445,
    "COUNTY": "CONTRA COSTA",
    "LATITUDE": 38.04457,
    "LONGITUDE": -122.25522,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 120200,
    "US_RANK": 58,
    "CRUDE": 120200,
    "URL": "https://drive.google.com/uc?id=1ryy4-9O7SniE0DXFqEne1QMGjp24L1zh"
  },
  {
    "OBJECTID": 20,
    "NAME": "TULSA WEST",
    "ADDRESS": "1700 S UNION AVE",
    "CITY": "TULSA",
    "STATE": "OK",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 285,
    "COUNTY": "TULSA",
    "LATITUDE": 36.1389,
    "LONGITUDE": -96.02106,
    "WEBSITE": "http://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER TULSA REFINING LLC",
    "CAPACITY": 85000,
    "US_RANK": 75,
    "CRUDE": 85000,
    "URL": "https://drive.google.com/uc?id=1N-leDmxDtMtj6IYJc6yqojkmswBihA11"
  },
  {
    "OBJECTID": 21,
    "NAME": "PARAMOUNT",
    "ADDRESS": "14700 DOWNEY AVENUE",
    "CITY": "PARAMOUNT",
    "STATE": "CA",
    "TYPE": "SMALL LOW COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 155,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.89872,
    "LONGITUDE": -118.14659,
    "WEBSITE": "http://www.ppcla.com",
    "OWNER": "ALON ISRAEL OIL COMPANY LTD",
    "OPERNAME": "PARAMOUNT PETROLEUM CORPORATION",
    "CAPACITY": 84500,
    "US_RANK": 77,
    "CRUDE": 0,
    "URL": "https://drive.google.com/uc?id=1AKyEAEs5Aq-5MsJhz3ailEYDS-SZ5GPi"
  },
  {
    "OBJECTID": 22,
    "NAME": "TULSA EAST",
    "ADDRESS": "902 W 25TH STREET",
    "CITY": "TULSA",
    "STATE": "OK",
    "TYPE": "LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 409,
    "COUNTY": "TULSA",
    "LATITUDE": 36.11992,
    "LONGITUDE": -96.00072,
    "WEBSITE": "https://www.hollyfrontier.com",
    "OWNER": "HOLLYFRONTIER CORP",
    "OPERNAME": "HOLLYFRONTIER TULSA REFINING LLC",
    "CAPACITY": 70300,
    "US_RANK": 87,
    "CRUDE": 0,
    "URL": "https://drive.google.com/uc?id=1OBMcnRrSiL2LtpfDE7UT3XO_EfVQFRSi"
  },
  {
    "OBJECTID": 23,
    "NAME": "MOUNT VERNON",
    "ADDRESS": "1200 REFINERY ROAD",
    "CITY": "MOUNT VERNON",
    "STATE": "IN",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 190,
    "COUNTY": "POSEY",
    "LATITUDE": 37.94216,
    "LONGITUDE": -87.91082,
    "WEBSITE": "http://www.countrymark.com",
    "OWNER": "COUNTRYMARK COOP INC",
    "OPERNAME": "COUNTRYMARK COOPERATIVE INC",
    "CAPACITY": 28200,
    "US_RANK": 110,
    "CRUDE": 28200,
    "URL": "https://drive.google.com/uc?id=1KrdyidaL20vk2Ac1KkxBgG1yhH6yi5zD"
  },
  {
    "OBJECTID": 24,
    "NAME": "NEWELL",
    "ADDRESS": "9995 OHIO RIVER BOULEVARD",
    "CITY": "NEWELL",
    "STATE": "WV",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 180,
    "COUNTY": "HANCOCK",
    "LATITUDE": 40.61127,
    "LONGITUDE": -80.62966,
    "WEBSITE": "http://www.ergon.com/",
    "OWNER": "ERGON INC",
    "OPERNAME": "ERGON WEST VIRGINIA INC",
    "CAPACITY": 22300,
    "US_RANK": 116,
    "CRUDE": 22300,
    "URL": "https://drive.google.com/uc?id=1KGDVEpj5bo63Fr5E5kyHPITOGivzaxrx"
  },
  {
    "OBJECTID": 25,
    "NAME": "WESTLAKE",
    "ADDRESS": "2800 OLD SPANISH TRAIL",
    "CITY": "WESTLAKE",
    "STATE": "LA",
    "TYPE": "MEDIUM LUBRICANTS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 98,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.24224,
    "LONGITUDE": -93.28476,
    "WEBSITE": "http://www.fhr.com",
    "OWNER": "EXCEL PARALUBES",
    "OPERNAME": "EXCEL PARALUBES",
    "CAPACITY": 0,
    "US_RANK": 139,
    "CRUDE": 0,
    "URL": "https://drive.google.com/uc?id=1_3Pm5AG9uIZ5A7M2_Ct3o6IdGz9_Z4Fp"
  },
  {
    "OBJECTID": 26,
    "NAME": "WESTLAKE",
    "ADDRESS": "2200 OLD SPANISH TRAIL",
    "CITY": "WESTLAKE",
    "STATE": "LA",
    "TYPE": "LARGE MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 705,
    "COUNTY": "CALCASIEU",
    "LATITUDE": 30.24116,
    "LONGITUDE": -93.27022,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 260000,
    "US_RANK": 21,
    "CRUDE": 260000,
    "URL": "https://drive.google.com/uc?id=1_PQkZuMPKO0l4Q_tAB4mC5aReGAtAHmw"
  },
  {
    "OBJECTID": 27,
    "NAME": "SAINT PAUL PARK",
    "ADDRESS": "301 ST PAUL PARK RD",
    "CITY": "SAINT PAUL PARK",
    "STATE": "MN",
    "TYPE": "MEDIUM REFINERY WITH HIGH COMPLEXITY",
    "STATUS": "IN SERVICE",
    "POPULATION": 370,
    "COUNTY": "WASHINGTON",
    "LATITUDE": 44.85156,
    "LONGITUDE": -93.00051,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 102000,
    "US_RANK": 63,
    "CRUDE": 98515,
    "URL": "https://drive.google.com/uc?id=1nd86st-whT6hzugm5sMGFHq1Nq-qZUk5"
  },
  {
    "OBJECTID": 28,
    "NAME": "BRADFORD",
    "ADDRESS": "77 N KENDALL AVE",
    "CITY": "BRADFORD",
    "STATE": "PA",
    "TYPE": "VERY SMALL REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 250,
    "COUNTY": "MCKEAN",
    "LATITUDE": 41.96487,
    "LONGITUDE": -78.63466,
    "WEBSITE": "http://www.amref.com",
    "OWNER": "AMERICAN REFINING GROUP INC",
    "OPERNAME": "AMERICAN REFINING GROUP INC",
    "CAPACITY": 11000,
    "US_RANK": 127,
    "CRUDE": 11000,
    "URL": "https://drive.google.com/uc?id=1-u_4Yt6mGk7eTDzdt6qM4VzD86UGINJv"
  },
  {
    "OBJECTID": 29,
    "NAME": "EVANSTON",
    "ADDRESS": "2990 COUNTY ROAD 180",
    "CITY": "EVANSTON",
    "STATE": "WY",
    "TYPE": "VERY SMALL SIMPLE REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 26,
    "COUNTY": "UINTA",
    "LATITUDE": 41.26035,
    "LONGITUDE": -110.80691,
    "WEBSITE": "http://silvereagleenergy.com",
    "OWNER": "SILVER EAGLE REFINING INC",
    "OPERNAME": "SILVER EAGLE REFINING",
    "CAPACITY": 3000,
    "US_RANK": 136,
    "CRUDE": 3000,
    "URL": "https://drive.google.com/uc?id=130BCixYXyfMaE4NmYf810WlwW5-NTLoy"
  },
  {
    "OBJECTID": 30,
    "NAME": "EWA BEACH",
    "ADDRESS": "91-325 KOMOHANA STREET",
    "CITY": "KAPOLEI",
    "STATE": "HI",
    "TYPE": "MEDIUM COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 260,
    "COUNTY": "HONOLULU",
    "LATITUDE": 21.30378,
    "LONGITUDE": -158.09246,
    "WEBSITE": "http://www.hawaiiindependentenergy.com",
    "OWNER": "PAR PETROLEUM INC",
    "OPERNAME": "HAWAII INDEPENDENT ENERGY LLC",
    "CAPACITY": 93500,
    "US_RANK": 68,
    "CRUDE": 93500,
    "URL": "https://drive.google.com/uc?id=1unUzGosPqTylFEKcl4s5cv2R4pgbDjUD"
  },
  {
    "OBJECTID": 31,
    "NAME": "LOS ANGELES (WILMINGTON PLANT)",
    "ADDRESS": "2101 E PACIFIC COAST HIGHWAY",
    "CITY": "WILMINGTON",
    "STATE": "CA",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 520,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.79637,
    "LONGITUDE": -118.23297,
    "WEBSITE": "https://www.marathonpetroleum.com",
    "OWNER": "MARATHON PETROLEUM CORP",
    "OPERNAME": "MARATHON PETROLEUM CO LP",
    "CAPACITY": 94900,
    "US_RANK": 67,
    "CRUDE": 94900,
    "URL": "https://drive.google.com/uc?id=1gnZ0ARi5K8GK5gYwg-X9Wq8l_AP3NG8P"
  },
  {
    "OBJECTID": 32,
    "NAME": "NORTH SALT LAKE",
    "ADDRESS": "333 W CENTER STREET",
    "CITY": "NORTH SALT LAKE",
    "STATE": "UT",
    "TYPE": "SMALL BUT MEDIUM COMPLEX REFINERY FOCUSED ON GASOLINE PRODUCTION",
    "STATUS": "IN SERVICE",
    "POPULATION": 146,
    "COUNTY": "DAVIS",
    "LATITUDE": 40.83864,
    "LONGITUDE": -111.92062,
    "WEBSITE": "http://www.bigwestoil.com",
    "OWNER": "FJ MANAGEMENT INC",
    "OPERNAME": "BIG WEST OIL CO",
    "CAPACITY": 30500,
    "US_RANK": 109,
    "CRUDE": 30500,
    "URL": "https://drive.google.com/uc?id=1LKhZ9F15l0TZ5L8ua2rXl2QZJ40MoHw8"
  },
  {
    "OBJECTID": 33,
    "NAME": "HONOLULU",
    "ADDRESS": "91-480 MALAKOLE STREET",
    "CITY": "KAPOLEI",
    "STATE": "HI",
    "TYPE": "MEDIUM SIZED MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 203,
    "COUNTY": "HONOLULU",
    "LATITUDE": 21.30988,
    "LONGITUDE": -158.1118,
    "WEBSITE": "https://www.islandenergyservices.com",
    "OWNER": "ISLAND ENERGY SERVICES LLC",
    "OPERNAME": "ISLAND ENERGY SERVICES DOWNSTREAM",
    "CAPACITY": 54000,
    "US_RANK": 98,
    "CRUDE": 54000,
    "URL": "https://drive.google.com/uc?id=1S38acLfwTOCNvlUmoYevvrRmD_hT3jor"
  },
  {
    "OBJECTID": 34,
    "NAME": "BATON ROUGE",
    "ADDRESS": "4045 SCENIC HIGHWAY",
    "CITY": "BATON ROUGE",
    "STATE": "LA",
    "TYPE": "VERY LARGE COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 1337,
    "COUNTY": "EAST BATON ROUGE",
    "LATITUDE": 30.4839,
    "LONGITUDE": -91.17958,
    "WEBSITE": "http://corporate.exxonmobil.com",
    "OWNER": "EXXON MOBIL CORP",
    "OPERNAME": "EXXONMOBIL REFINING & SUPPLY CO",
    "CAPACITY": 502500,
    "US_RANK": 4,
    "CRUDE": 502500,
    "URL": "https://drive.google.com/uc?id=1rE5wpKPnN6yGNpSLPgNxpaTtYURgeF0G"
  },
  {
    "OBJECTID": 35,
    "NAME": "WILMINGTON",
    "ADDRESS": "1660 W. ANAHEIM STREET",
    "CITY": "WILMINGTON",
    "STATE": "CA",
    "TYPE": "MEDIUM SIZED COMPLEX REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 411,
    "COUNTY": "LOS ANGELES",
    "LATITUDE": 33.77309,
    "LONGITUDE": -118.28705,
    "WEBSITE": "http://www.phillips66.com",
    "OWNER": "PHILLIPS 66 COMPANY",
    "OPERNAME": "PHILLIPS 66 COMPANY",
    "CAPACITY": 139000,
    "US_RANK": 54,
    "CRUDE": 139000,
    "URL": "https://drive.google.com/uc?id=1Efw3bhjQmDYOkxr3oaJD2CVrks8dkQus"
  },
  {
    "OBJECTID": 36,
    "NAME": "TACOMA",
    "ADDRESS": "3001 MARSHALL AVENUE",
    "CITY": "TACOMA",
    "STATE": "WA",
    "TYPE": "SMALL MEDIUM COMPLEXITY REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 170,
    "COUNTY": "PIERCE",
    "LATITUDE": 47.25709,
    "LONGITUDE": -122.39626,
    "WEBSITE": "http://www.usor.com",
    "OWNER": "TRAILSTONE LP",
    "OPERNAME": "US OIL & REFINING CO",
    "CAPACITY": 40700,
    "US_RANK": 103,
    "CRUDE": 40700,
    "URL": "https://drive.google.com/uc?id=1wovqPhfLq6Kmjfv5_PqdZB0Cv48L5EhE"
  },
  {
    "OBJECTID": 37,
    "NAME": "COTTON VALLEY",
    "ADDRESS": "1756 OLD HWY 7",
    "CITY": "COTTON VALLEY",
    "STATE": "LA",
    "TYPE": "SMALL LUBRICANTS REFINERY",
    "STATUS": "IN SERVICE",
    "POPULATION": 42,
    "COUNTY": "WEBSTER",
    "LATITUDE": 32.79952,
    "LONGITUDE": -93.41136,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET LUBRICANTS CO LP",
    "CAPACITY": 13020,
    "US_RANK": 125,
    "CRUDE": 13020,
    "URL": "https://drive.google.com/uc?id=1b5cFzlFN_zqqJpOdfan3BlA541MnzTS4"
  },
  {
    "OBJECTID": 38,
    "NAME": "GREAT FALLS",
    "ADDRESS": "1900 10TH STREET NE",
    "CITY": "GREAT FALLS",
    "STATE": "MT",
    "TYPE": "VERY SMALL BUT COMPLEX REFINERY CAPABLE OF PROCESSING THE HEAVIEST CRUDE",
    "STATUS": "IN SERVICE",
    "POPULATION": 95,
    "COUNTY": "CASCADE",
    "LATITUDE": 47.52363,
    "LONGITUDE": -111.29321,
    "WEBSITE": "http://www.calumetspecialty.com",
    "OWNER": "CALUMET SPECIALTY PRODUCTS PARTNERS, L.P.",
    "OPERNAME": "CALUMET MONTANA REFINING LLC",
    "CAPACITY": 33600,
    "US_RANK": 108,
    "CRUDE": 24000,
    "URL": "https://drive.google.com/uc?id=1Kkvq2lHpUvhFb2T5wJP3QMU8mc8gvMH6"
  }
]
*/

fetch("../data/db.json")

const dataset = JSON.parse(JSON.stringify(data))

console.log(dataset)

const cardContainer = document.getElementById('card-container');

function renderData(dataset) {
    for (let i = 0; i < dataset.length; i++){
      const card = document.createElement("div");
      card.classList.add("card");

      const hoverContainer = document.createElement("div");
      hoverContainer.classList.add("hoverWrapper");

      const image = document.createElement("img");
      image.setAttribute("src", dataset[i].URL);

      const title = document.createElement("p");
      title.textContent = `${dataset[i].NAME} REFINERY`;

      hoverContainer.appendChild(image)
      hoverContainer.appendChild(title)

      card.appendChild(hoverContainer)
      
      cardContainer.appendChild(card);
    }
}

renderData(dataset);
